//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Falls die Abweichung eines Bauvorhabens von öffentlich-rechtlichen Bestimmungen bearbeitet (und damit zugelassen bzw. nicht zugelassen) wurde, dient dieser Typ im entsprechenden Kontext zur Übermittlung der relevanten Parameter.
 * 
 * <p>Java class for AbweichungBearbeitet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbweichungBearbeitet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="istZugelassen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="art" type="{http://www.is-argebau.de/xbau/2}Code.AbweichungArt"/>
 *         &lt;element name="vorschrift" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *         &lt;element name="begruendung" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
 *         &lt;element name="nebenbestimmung" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbweichungBearbeitet", propOrder = {
    "istZugelassen",
    "art",
    "vorschrift",
    "begruendung",
    "nebenbestimmung"
})
public class AbweichungBearbeitet {

    protected boolean istZugelassen;
    @XmlElement(required = true)
    protected CodeAbweichungArt art;
    @XmlElement(required = true)
    protected Text vorschrift;
    protected Text begruendung;
    protected Text nebenbestimmung;

    /**
     * Gets the value of the istZugelassen property.
     * 
     */
    public boolean isIstZugelassen() {
        return istZugelassen;
    }

    /**
     * Sets the value of the istZugelassen property.
     * 
     */
    public void setIstZugelassen(boolean value) {
        this.istZugelassen = value;
    }

    /**
     * Gets the value of the art property.
     * 
     * @return
     *     possible object is
     *     {@link CodeAbweichungArt }
     *     
     */
    public CodeAbweichungArt getArt() {
        return art;
    }

    /**
     * Sets the value of the art property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeAbweichungArt }
     *     
     */
    public void setArt(CodeAbweichungArt value) {
        this.art = value;
    }

    /**
     * Gets the value of the vorschrift property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getVorschrift() {
        return vorschrift;
    }

    /**
     * Sets the value of the vorschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setVorschrift(Text value) {
        this.vorschrift = value;
    }

    /**
     * Gets the value of the begruendung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getBegruendung() {
        return begruendung;
    }

    /**
     * Sets the value of the begruendung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setBegruendung(Text value) {
        this.begruendung = value;
    }

    /**
     * Gets the value of the nebenbestimmung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getNebenbestimmung() {
        return nebenbestimmung;
    }

    /**
     * Sets the value of the nebenbestimmung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setNebenbestimmung(Text value) {
        this.nebenbestimmung = value;
    }

}
