//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Durch den Typ Akteur wird eine Differenzierung zwischen  natürlichen Einzelpersonen, Personengruppen und juristischen Personen definiert.
 * Im Namen einer Firma handelt eine natürliche Person als Vertreter. Bei mehreren Personen (z.B. Eigentümergemeinschaften) wird jede Person (juristisch oder nätürlich) als Akteur definiert. Eine Person dieser Gruppe kann als Vertreter definiert werden.
 * 
 * <p>Java class for Akteur complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Akteur">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="natuerlichePerson" type="{http://www.is-argebau.de/xbau/2}AmBauBeteiligtePerson" minOccurs="0"/>
 *         &lt;element name="organisation" type="{http://www.is-argebau.de/xbau/2}Organisation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Akteur", propOrder = {
    "natuerlichePerson",
    "organisation"
})
public class Akteur {

    protected AmBauBeteiligtePerson natuerlichePerson;
    protected Organisation organisation;

    /**
     * Gets the value of the natuerlichePerson property.
     * 
     * @return
     *     possible object is
     *     {@link AmBauBeteiligtePerson }
     *     
     */
    public AmBauBeteiligtePerson getNatuerlichePerson() {
        return natuerlichePerson;
    }

    /**
     * Sets the value of the natuerlichePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmBauBeteiligtePerson }
     *     
     */
    public void setNatuerlichePerson(AmBauBeteiligtePerson value) {
        this.natuerlichePerson = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation }
     *     
     */
    public Organisation getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation }
     *     
     */
    public void setOrganisation(Organisation value) {
        this.organisation = value;
    }

}
