//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ fasst die Merkmale zusammen, die typischerweise zu am Bau beteiligten natürlichen Personen genannt werden bzw. zu nennen sind.
 * 
 * <p>Java class for AmBauBeteiligtePerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AmBauBeteiligtePerson">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.is-argebau.de/xbau/2}NameNatuerlichePerson"/>
 *         &lt;element name="anschrift" type="{http://www.is-argebau.de/xbau/2}Anschrift"/>
 *         &lt;element name="kommunikation" type="{http://www.is-argebau.de/xbau/2}Kommunikation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmBauBeteiligtePerson", propOrder = {
    "name",
    "anschrift",
    "kommunikation"
})
public class AmBauBeteiligtePerson {

    @XmlElement(required = true)
    protected NameNatuerlichePerson name;
    @XmlElement(required = true)
    protected Anschrift anschrift;
    protected List<Kommunikation> kommunikation;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameNatuerlichePerson }
     *     
     */
    public NameNatuerlichePerson getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameNatuerlichePerson }
     *     
     */
    public void setName(NameNatuerlichePerson value) {
        this.name = value;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link Anschrift }
     *     
     */
    public Anschrift getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anschrift }
     *     
     */
    public void setAnschrift(Anschrift value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the kommunikation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kommunikation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKommunikation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kommunikation }
     * 
     * 
     */
    public List<Kommunikation> getKommunikation() {
        if (kommunikation == null) {
            kommunikation = new ArrayList<Kommunikation>();
        }
        return this.kommunikation;
    }

}
