//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Dieser Typ nimmt die Metadaten zu einer Bauvorlage bzw. sonstigen Anlage auf, die einem Antrag als Anlage beigefügt ist.
 * 
 * <p>Java class for AnlageBauvorlage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnlageBauvorlage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bezeichnung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *         &lt;element name="versionsnummer" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="bauvorlageart">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="vorlageBauvorhaben" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauantragBauvorhaben"/>
 *                   &lt;element name="vorlageBauantragBearbeitung" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauantragBearbeitung"/>
 *                   &lt;element name="vorlageBauzustand" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauzustand"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mimeType" type="{http://www.is-argebau.de/xbau/2}Code.XBau-MimeType"/>
 *         &lt;element name="primaerdokument" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="referenzPrimaerdokument" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="dateinameAnhang" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnlageBauvorlage", propOrder = {
    "bezeichnung",
    "versionsnummer",
    "datum",
    "bauvorlageart",
    "mimeType",
    "primaerdokument",
    "referenzPrimaerdokument",
    "dateinameAnhang"
})
public class AnlageBauvorlage {

    @XmlElement(required = true)
    protected String bezeichnung;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger versionsnummer;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(required = true)
    protected AnlageBauvorlage.Bauvorlageart bauvorlageart;
    @XmlElement(required = true)
    protected CodeXBauMimeType mimeType;
    protected byte[] primaerdokument;
    @XmlSchemaType(name = "anyURI")
    protected String referenzPrimaerdokument;
    protected String dateinameAnhang;

    /**
     * Gets the value of the bezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnung() {
        return bezeichnung;
    }

    /**
     * Sets the value of the bezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnung(String value) {
        this.bezeichnung = value;
    }

    /**
     * Gets the value of the versionsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionsnummer() {
        return versionsnummer;
    }

    /**
     * Sets the value of the versionsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionsnummer(BigInteger value) {
        this.versionsnummer = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the bauvorlageart property.
     * 
     * @return
     *     possible object is
     *     {@link AnlageBauvorlage.Bauvorlageart }
     *     
     */
    public AnlageBauvorlage.Bauvorlageart getBauvorlageart() {
        return bauvorlageart;
    }

    /**
     * Sets the value of the bauvorlageart property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnlageBauvorlage.Bauvorlageart }
     *     
     */
    public void setBauvorlageart(AnlageBauvorlage.Bauvorlageart value) {
        this.bauvorlageart = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeXBauMimeType }
     *     
     */
    public CodeXBauMimeType getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeXBauMimeType }
     *     
     */
    public void setMimeType(CodeXBauMimeType value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the primaerdokument property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPrimaerdokument() {
        return primaerdokument;
    }

    /**
     * Sets the value of the primaerdokument property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPrimaerdokument(byte[] value) {
        this.primaerdokument = value;
    }

    /**
     * Gets the value of the referenzPrimaerdokument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenzPrimaerdokument() {
        return referenzPrimaerdokument;
    }

    /**
     * Sets the value of the referenzPrimaerdokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenzPrimaerdokument(String value) {
        this.referenzPrimaerdokument = value;
    }

    /**
     * Gets the value of the dateinameAnhang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateinameAnhang() {
        return dateinameAnhang;
    }

    /**
     * Sets the value of the dateinameAnhang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateinameAnhang(String value) {
        this.dateinameAnhang = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="vorlageBauvorhaben" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauantragBauvorhaben"/>
     *         &lt;element name="vorlageBauantragBearbeitung" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauantragBearbeitung"/>
     *         &lt;element name="vorlageBauzustand" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauzustand"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vorlageBauvorhaben",
        "vorlageBauantragBearbeitung",
        "vorlageBauzustand"
    })
    public static class Bauvorlageart {

        protected CodeVorlagenBauantragBauvorhaben vorlageBauvorhaben;
        protected CodeVorlagenBauantragBearbeitung vorlageBauantragBearbeitung;
        protected CodeVorlagenBauzustand vorlageBauzustand;

        /**
         * Gets the value of the vorlageBauvorhaben property.
         * 
         * @return
         *     possible object is
         *     {@link CodeVorlagenBauantragBauvorhaben }
         *     
         */
        public CodeVorlagenBauantragBauvorhaben getVorlageBauvorhaben() {
            return vorlageBauvorhaben;
        }

        /**
         * Sets the value of the vorlageBauvorhaben property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeVorlagenBauantragBauvorhaben }
         *     
         */
        public void setVorlageBauvorhaben(CodeVorlagenBauantragBauvorhaben value) {
            this.vorlageBauvorhaben = value;
        }

        /**
         * Gets the value of the vorlageBauantragBearbeitung property.
         * 
         * @return
         *     possible object is
         *     {@link CodeVorlagenBauantragBearbeitung }
         *     
         */
        public CodeVorlagenBauantragBearbeitung getVorlageBauantragBearbeitung() {
            return vorlageBauantragBearbeitung;
        }

        /**
         * Sets the value of the vorlageBauantragBearbeitung property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeVorlagenBauantragBearbeitung }
         *     
         */
        public void setVorlageBauantragBearbeitung(CodeVorlagenBauantragBearbeitung value) {
            this.vorlageBauantragBearbeitung = value;
        }

        /**
         * Gets the value of the vorlageBauzustand property.
         * 
         * @return
         *     possible object is
         *     {@link CodeVorlagenBauzustand }
         *     
         */
        public CodeVorlagenBauzustand getVorlageBauzustand() {
            return vorlageBauzustand;
        }

        /**
         * Sets the value of the vorlageBauzustand property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeVorlagenBauzustand }
         *     
         */
        public void setVorlageBauzustand(CodeVorlagenBauzustand value) {
            this.vorlageBauzustand = value;
        }

    }

}
