//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ beinhaltet die Parameter eines Beteiligungsanliegens der Bauaufsichtsbehörde gegenüber einem Träger öffentlicher Belange.
 * 
 * <p>Java class for AnliegenBeteiligung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnliegenBeteiligung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rolle" type="{http://www.is-argebau.de/xbau/2}Code.BeteiligungRolle"/>
 *         &lt;element name="rechtsbereich" type="{http://www.is-argebau.de/xbau/2}Code.Rechtsbereich"/>
 *         &lt;element name="grundDerBeteiligung" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *         &lt;element name="strukturierteStellungnahme" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnliegenBeteiligung", propOrder = {
    "rolle",
    "rechtsbereich",
    "grundDerBeteiligung",
    "strukturierteStellungnahme"
})
public class AnliegenBeteiligung {

    @XmlElement(required = true)
    protected CodeBeteiligungRolle rolle;
    @XmlElement(required = true)
    protected CodeRechtsbereich rechtsbereich;
    @XmlElement(required = true)
    protected Text grundDerBeteiligung;
    protected boolean strukturierteStellungnahme;

    /**
     * Gets the value of the rolle property.
     * 
     * @return
     *     possible object is
     *     {@link CodeBeteiligungRolle }
     *     
     */
    public CodeBeteiligungRolle getRolle() {
        return rolle;
    }

    /**
     * Sets the value of the rolle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeBeteiligungRolle }
     *     
     */
    public void setRolle(CodeBeteiligungRolle value) {
        this.rolle = value;
    }

    /**
     * Gets the value of the rechtsbereich property.
     * 
     * @return
     *     possible object is
     *     {@link CodeRechtsbereich }
     *     
     */
    public CodeRechtsbereich getRechtsbereich() {
        return rechtsbereich;
    }

    /**
     * Sets the value of the rechtsbereich property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeRechtsbereich }
     *     
     */
    public void setRechtsbereich(CodeRechtsbereich value) {
        this.rechtsbereich = value;
    }

    /**
     * Gets the value of the grundDerBeteiligung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getGrundDerBeteiligung() {
        return grundDerBeteiligung;
    }

    /**
     * Sets the value of the grundDerBeteiligung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setGrundDerBeteiligung(Text value) {
        this.grundDerBeteiligung = value;
    }

    /**
     * Gets the value of the strukturierteStellungnahme property.
     * 
     */
    public boolean isStrukturierteStellungnahme() {
        return strukturierteStellungnahme;
    }

    /**
     * Sets the value of the strukturierteStellungnahme property.
     * 
     */
    public void setStrukturierteStellungnahme(boolean value) {
        this.strukturierteStellungnahme = value;
    }

}
