//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.is-argebau.de/xbau/2}Nachricht.privat2G">
 *       &lt;sequence>
 *         &lt;element name="bezug" type="{http://www.is-argebau.de/xbau/2}Bezug"/>
 *         &lt;element name="stellungnahme" type="{http://www.is-argebau.de/xbau/2}StellungnahmeBelastenderVerwaltungsakt" maxOccurs="unbounded"/>
 *         &lt;element name="bauvorhabenAenderungsdaten" type="{http://www.is-argebau.de/xbau/2}Bauvorhaben" minOccurs="0"/>
 *         &lt;element name="anlagen" type="{http://www.is-argebau.de/xbau/2}Anlagen" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bezug",
    "stellungnahme",
    "bauvorhabenAenderungsdaten",
    "anlagen"
})
@XmlRootElement(name = "baugenehmigung.stellungnahme.0204")
public class BaugenehmigungStellungnahme0204
    extends NachrichtPrivat2G
{

    @XmlElement(required = true)
    protected Bezug bezug;
    @XmlElement(required = true)
    protected List<StellungnahmeBelastenderVerwaltungsakt> stellungnahme;
    protected Bauvorhaben bauvorhabenAenderungsdaten;
    protected Anlagen anlagen;

    /**
     * Gets the value of the bezug property.
     * 
     * @return
     *     possible object is
     *     {@link Bezug }
     *     
     */
    public Bezug getBezug() {
        return bezug;
    }

    /**
     * Sets the value of the bezug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bezug }
     *     
     */
    public void setBezug(Bezug value) {
        this.bezug = value;
    }

    /**
     * Gets the value of the stellungnahme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stellungnahme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStellungnahme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StellungnahmeBelastenderVerwaltungsakt }
     * 
     * 
     */
    public List<StellungnahmeBelastenderVerwaltungsakt> getStellungnahme() {
        if (stellungnahme == null) {
            stellungnahme = new ArrayList<StellungnahmeBelastenderVerwaltungsakt>();
        }
        return this.stellungnahme;
    }

    /**
     * Gets the value of the bauvorhabenAenderungsdaten property.
     * 
     * @return
     *     possible object is
     *     {@link Bauvorhaben }
     *     
     */
    public Bauvorhaben getBauvorhabenAenderungsdaten() {
        return bauvorhabenAenderungsdaten;
    }

    /**
     * Sets the value of the bauvorhabenAenderungsdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bauvorhaben }
     *     
     */
    public void setBauvorhabenAenderungsdaten(Bauvorhaben value) {
        this.bauvorhabenAenderungsdaten = value;
    }

    /**
     * Gets the value of the anlagen property.
     * 
     * @return
     *     possible object is
     *     {@link Anlagen }
     *     
     */
    public Anlagen getAnlagen() {
        return anlagen;
    }

    /**
     * Sets the value of the anlagen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anlagen }
     *     
     */
    public void setAnlagen(Anlagen value) {
        this.anlagen = value;
    }

}
