//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Das Baugrundstück ist der Ort der Baumaßnahme. Dieser kann aus mehreren Grundstücken im Sinne des Grundbuchs bestehen. Ein Grundstück kann aus mehreren Fluren bzw. Flurstücken bestehen.
 * 
 * <p>Java class for Baugrundstueck complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Baugrundstueck">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anschrift" type="{http://www.is-argebau.de/xbau/2}AnschriftBaugrundstueck" minOccurs="0"/>
 *         &lt;element name="flurstueckkennzeichnung" type="{http://www.is-argebau.de/xbau/2}FlurstueckKennzeichnung"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Baugrundstueck", propOrder = {
    "anschrift",
    "flurstueckkennzeichnung"
})
public class Baugrundstueck {

    protected AnschriftBaugrundstueck anschrift;
    @XmlElement(required = true)
    protected FlurstueckKennzeichnung flurstueckkennzeichnung;

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftBaugrundstueck }
     *     
     */
    public AnschriftBaugrundstueck getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftBaugrundstueck }
     *     
     */
    public void setAnschrift(AnschriftBaugrundstueck value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the flurstueckkennzeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link FlurstueckKennzeichnung }
     *     
     */
    public FlurstueckKennzeichnung getFlurstueckkennzeichnung() {
        return flurstueckkennzeichnung;
    }

    /**
     * Sets the value of the flurstueckkennzeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlurstueckKennzeichnung }
     *     
     */
    public void setFlurstueckkennzeichnung(FlurstueckKennzeichnung value) {
        this.flurstueckkennzeichnung = value;
    }

}
