//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.is-argebau.de/xbau/2}Nachricht.G2privat">
 *       &lt;sequence>
 *         &lt;element name="bezug" type="{http://www.is-argebau.de/xbau/2}Bezug"/>
 *         &lt;element name="bescheid" type="{http://www.is-argebau.de/xbau/2}Bescheid"/>
 *         &lt;element name="anlagen" type="{http://www.is-argebau.de/xbau/2}Anlagen"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bezug",
    "bescheid",
    "anlagen"
})
@XmlRootElement(name = "baugenehmigung.bescheid.0205")
public class BaugenehmigungBescheid0205
    extends NachrichtG2Privat
{

    @XmlElement(required = true)
    protected Bezug bezug;
    @XmlElement(required = true)
    protected Bescheid bescheid;
    @XmlElement(required = true)
    protected Anlagen anlagen;

    /**
     * Gets the value of the bezug property.
     * 
     * @return
     *     possible object is
     *     {@link Bezug }
     *     
     */
    public Bezug getBezug() {
        return bezug;
    }

    /**
     * Sets the value of the bezug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bezug }
     *     
     */
    public void setBezug(Bezug value) {
        this.bezug = value;
    }

    /**
     * Gets the value of the bescheid property.
     * 
     * @return
     *     possible object is
     *     {@link Bescheid }
     *     
     */
    public Bescheid getBescheid() {
        return bescheid;
    }

    /**
     * Sets the value of the bescheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bescheid }
     *     
     */
    public void setBescheid(Bescheid value) {
        this.bescheid = value;
    }

    /**
     * Gets the value of the anlagen property.
     * 
     * @return
     *     possible object is
     *     {@link Anlagen }
     *     
     */
    public Anlagen getAnlagen() {
        return anlagen;
    }

    /**
     * Sets the value of the anlagen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anlagen }
     *     
     */
    public void setAnlagen(Anlagen value) {
        this.anlagen = value;
    }

}
