//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ beinhaltet die Parameter für das Maß der baulichen Nutzung.
 * 
 * <p>Java class for BaulicheNutzungMass complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaulicheNutzungMass">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hoeheDerBaulichenAnlage" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="anzahlVollgeschosse" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="grundflaechenDerBaulichenAnlage" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="geschossflaeche" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="baumasse" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="verkaufsflaeche" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="grundstuecksflaechen" type="{http://www.is-argebau.de/xbau/2}Grundstuecksflaechen" minOccurs="0"/>
 *         &lt;element name="staedtebaulicheKennzahlen" type="{http://www.is-argebau.de/xbau/2}StaedtebaulicheKennzahlen" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nutzungseinheiten" type="{http://www.is-argebau.de/xbau/2}Nutzungseinheiten" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaulicheNutzungMass", propOrder = {
    "hoeheDerBaulichenAnlage",
    "anzahlVollgeschosse",
    "grundflaechenDerBaulichenAnlage",
    "geschossflaeche",
    "baumasse",
    "verkaufsflaeche",
    "grundstuecksflaechen",
    "staedtebaulicheKennzahlen",
    "nutzungseinheiten"
})
public class BaulicheNutzungMass {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger hoeheDerBaulichenAnlage;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger anzahlVollgeschosse;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger grundflaechenDerBaulichenAnlage;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger geschossflaeche;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger baumasse;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger verkaufsflaeche;
    protected Grundstuecksflaechen grundstuecksflaechen;
    protected List<StaedtebaulicheKennzahlen> staedtebaulicheKennzahlen;
    protected Nutzungseinheiten nutzungseinheiten;

    /**
     * Gets the value of the hoeheDerBaulichenAnlage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHoeheDerBaulichenAnlage() {
        return hoeheDerBaulichenAnlage;
    }

    /**
     * Sets the value of the hoeheDerBaulichenAnlage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHoeheDerBaulichenAnlage(BigInteger value) {
        this.hoeheDerBaulichenAnlage = value;
    }

    /**
     * Gets the value of the anzahlVollgeschosse property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlVollgeschosse() {
        return anzahlVollgeschosse;
    }

    /**
     * Sets the value of the anzahlVollgeschosse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlVollgeschosse(BigInteger value) {
        this.anzahlVollgeschosse = value;
    }

    /**
     * Gets the value of the grundflaechenDerBaulichenAnlage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrundflaechenDerBaulichenAnlage() {
        return grundflaechenDerBaulichenAnlage;
    }

    /**
     * Sets the value of the grundflaechenDerBaulichenAnlage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrundflaechenDerBaulichenAnlage(BigInteger value) {
        this.grundflaechenDerBaulichenAnlage = value;
    }

    /**
     * Gets the value of the geschossflaeche property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGeschossflaeche() {
        return geschossflaeche;
    }

    /**
     * Sets the value of the geschossflaeche property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGeschossflaeche(BigInteger value) {
        this.geschossflaeche = value;
    }

    /**
     * Gets the value of the baumasse property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBaumasse() {
        return baumasse;
    }

    /**
     * Sets the value of the baumasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBaumasse(BigInteger value) {
        this.baumasse = value;
    }

    /**
     * Gets the value of the verkaufsflaeche property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVerkaufsflaeche() {
        return verkaufsflaeche;
    }

    /**
     * Sets the value of the verkaufsflaeche property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVerkaufsflaeche(BigInteger value) {
        this.verkaufsflaeche = value;
    }

    /**
     * Gets the value of the grundstuecksflaechen property.
     * 
     * @return
     *     possible object is
     *     {@link Grundstuecksflaechen }
     *     
     */
    public Grundstuecksflaechen getGrundstuecksflaechen() {
        return grundstuecksflaechen;
    }

    /**
     * Sets the value of the grundstuecksflaechen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grundstuecksflaechen }
     *     
     */
    public void setGrundstuecksflaechen(Grundstuecksflaechen value) {
        this.grundstuecksflaechen = value;
    }

    /**
     * Gets the value of the staedtebaulicheKennzahlen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the staedtebaulicheKennzahlen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStaedtebaulicheKennzahlen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StaedtebaulicheKennzahlen }
     * 
     * 
     */
    public List<StaedtebaulicheKennzahlen> getStaedtebaulicheKennzahlen() {
        if (staedtebaulicheKennzahlen == null) {
            staedtebaulicheKennzahlen = new ArrayList<StaedtebaulicheKennzahlen>();
        }
        return this.staedtebaulicheKennzahlen;
    }

    /**
     * Gets the value of the nutzungseinheiten property.
     * 
     * @return
     *     possible object is
     *     {@link Nutzungseinheiten }
     *     
     */
    public Nutzungseinheiten getNutzungseinheiten() {
        return nutzungseinheiten;
    }

    /**
     * Sets the value of the nutzungseinheiten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nutzungseinheiten }
     *     
     */
    public void setNutzungseinheiten(Nutzungseinheiten value) {
        this.nutzungseinheiten = value;
    }

}
