//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Eine Instanz dieses Typs stellt in Bezug auf den Gegenstand des Bauvorhabens (Vorhabens) die wichtigsten bauordnungsrechtlichen Parameter zusammen.
 * 
 * <p>Java class for BauordnungsrechtlicheKlassifikation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BauordnungsrechtlicheKlassifikation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gebaeudeklasse" type="{http://www.is-argebau.de/xbau/2}Code.Gebaeudeklasse" minOccurs="0"/>
 *         &lt;element name="sonderbau" type="{http://www.is-argebau.de/xbau/2}Code.Sonderbauten" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="garage" type="{http://www.is-argebau.de/xbau/2}Code.Garagentyp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BauordnungsrechtlicheKlassifikation", propOrder = {
    "gebaeudeklasse",
    "sonderbau",
    "garage"
})
public class BauordnungsrechtlicheKlassifikation {

    protected CodeGebaeudeklasse gebaeudeklasse;
    protected List<CodeSonderbauten> sonderbau;
    protected CodeGaragentyp garage;

    /**
     * Gets the value of the gebaeudeklasse property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGebaeudeklasse }
     *     
     */
    public CodeGebaeudeklasse getGebaeudeklasse() {
        return gebaeudeklasse;
    }

    /**
     * Sets the value of the gebaeudeklasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGebaeudeklasse }
     *     
     */
    public void setGebaeudeklasse(CodeGebaeudeklasse value) {
        this.gebaeudeklasse = value;
    }

    /**
     * Gets the value of the sonderbau property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sonderbau property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSonderbau().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeSonderbauten }
     * 
     * 
     */
    public List<CodeSonderbauten> getSonderbau() {
        if (sonderbau == null) {
            sonderbau = new ArrayList<CodeSonderbauten>();
        }
        return this.sonderbau;
    }

    /**
     * Gets the value of the garage property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGaragentyp }
     *     
     */
    public CodeGaragentyp getGarage() {
        return garage;
    }

    /**
     * Sets the value of the garage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGaragentyp }
     *     
     */
    public void setGarage(CodeGaragentyp value) {
        this.garage = value;
    }

}
