//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Typ für die Daten eines Bauvorhabens, enthält Informationen zum Wer, Was und Wo des Bauvorhabens bzw. Vorhabens. Der Begriff 'Bauvorhaben' wird hier sehr weit gefasst, so dass auch Nutzungsänderungen ohne Baumaßnahmen abgedeckt sind. Der Typ wird in allen Nachrichten eingesetzt, in denen Eigenschaften eines Bauvorhabens (bzw. Vorhabens) anzugeben sind bzw. geprüft werden sollen. Er wird auch da eingesetzt, wo über ein Bauvorhaben (Vorhaben) oder über Maßnahmen im Zusammenhang eines Bauvorhabens (Vorhabens) zu informieren ist.
 * 
 * <p>Java class for Bauvorhaben complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bauvorhaben">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bezeichnungDesBauvorhabens" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *         &lt;element name="beteiligte" type="{http://www.is-argebau.de/xbau/2}BeteiligteBauprojektInPlanung"/>
 *         &lt;element name="gegenstand">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="artDerMassnahme" type="{http://www.is-argebau.de/xbau/2}Code.BaumassnahmeArt"/>
 *                   &lt;element name="artDerBaulichenAnlage">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="artDesGebaeudes" type="{http://www.is-argebau.de/xbau/2}Code.BaulicheAnlagenGebaeude"/>
 *                             &lt;element name="artDerSonstigenAnlage" type="{http://www.is-argebau.de/xbau/2}Code.BaulicheAnlagenSonstige"/>
 *                             &lt;element name="artNichtAufgefuehrt" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="bauvorhabenDatenblatt" type="{http://www.is-argebau.de/xbau/2}Datenblatt"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="verortung">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="baugrundstueck" type="{http://www.is-argebau.de/xbau/2}Baugrundstueck" maxOccurs="unbounded"/>
 *                   &lt;element name="lageBauvorhaben" type="{http://www.is-argebau.de/xbau/2}GeoreferenzierteLage" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bauvorhaben", propOrder = {
    "bezeichnungDesBauvorhabens",
    "beteiligte",
    "gegenstand",
    "verortung"
})
public class Bauvorhaben {

    @XmlElement(required = true)
    protected String bezeichnungDesBauvorhabens;
    @XmlElement(required = true)
    protected BeteiligteBauprojektInPlanung beteiligte;
    @XmlElement(required = true)
    protected Bauvorhaben.Gegenstand gegenstand;
    @XmlElement(required = true)
    protected Bauvorhaben.Verortung verortung;

    /**
     * Gets the value of the bezeichnungDesBauvorhabens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnungDesBauvorhabens() {
        return bezeichnungDesBauvorhabens;
    }

    /**
     * Sets the value of the bezeichnungDesBauvorhabens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnungDesBauvorhabens(String value) {
        this.bezeichnungDesBauvorhabens = value;
    }

    /**
     * Gets the value of the beteiligte property.
     * 
     * @return
     *     possible object is
     *     {@link BeteiligteBauprojektInPlanung }
     *     
     */
    public BeteiligteBauprojektInPlanung getBeteiligte() {
        return beteiligte;
    }

    /**
     * Sets the value of the beteiligte property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeteiligteBauprojektInPlanung }
     *     
     */
    public void setBeteiligte(BeteiligteBauprojektInPlanung value) {
        this.beteiligte = value;
    }

    /**
     * Gets the value of the gegenstand property.
     * 
     * @return
     *     possible object is
     *     {@link Bauvorhaben.Gegenstand }
     *     
     */
    public Bauvorhaben.Gegenstand getGegenstand() {
        return gegenstand;
    }

    /**
     * Sets the value of the gegenstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bauvorhaben.Gegenstand }
     *     
     */
    public void setGegenstand(Bauvorhaben.Gegenstand value) {
        this.gegenstand = value;
    }

    /**
     * Gets the value of the verortung property.
     * 
     * @return
     *     possible object is
     *     {@link Bauvorhaben.Verortung }
     *     
     */
    public Bauvorhaben.Verortung getVerortung() {
        return verortung;
    }

    /**
     * Sets the value of the verortung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bauvorhaben.Verortung }
     *     
     */
    public void setVerortung(Bauvorhaben.Verortung value) {
        this.verortung = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="artDerMassnahme" type="{http://www.is-argebau.de/xbau/2}Code.BaumassnahmeArt"/>
     *         &lt;element name="artDerBaulichenAnlage">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="artDesGebaeudes" type="{http://www.is-argebau.de/xbau/2}Code.BaulicheAnlagenGebaeude"/>
     *                   &lt;element name="artDerSonstigenAnlage" type="{http://www.is-argebau.de/xbau/2}Code.BaulicheAnlagenSonstige"/>
     *                   &lt;element name="artNichtAufgefuehrt" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="bauvorhabenDatenblatt" type="{http://www.is-argebau.de/xbau/2}Datenblatt"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "artDerMassnahme",
        "artDerBaulichenAnlage",
        "bauvorhabenDatenblatt"
    })
    public static class Gegenstand {

        @XmlElement(required = true)
        protected CodeBaumassnahmeArt artDerMassnahme;
        @XmlElement(required = true)
        protected Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage artDerBaulichenAnlage;
        @XmlElement(required = true)
        protected Datenblatt bauvorhabenDatenblatt;

        /**
         * Gets the value of the artDerMassnahme property.
         * 
         * @return
         *     possible object is
         *     {@link CodeBaumassnahmeArt }
         *     
         */
        public CodeBaumassnahmeArt getArtDerMassnahme() {
            return artDerMassnahme;
        }

        /**
         * Sets the value of the artDerMassnahme property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeBaumassnahmeArt }
         *     
         */
        public void setArtDerMassnahme(CodeBaumassnahmeArt value) {
            this.artDerMassnahme = value;
        }

        /**
         * Gets the value of the artDerBaulichenAnlage property.
         * 
         * @return
         *     possible object is
         *     {@link Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage }
         *     
         */
        public Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage getArtDerBaulichenAnlage() {
            return artDerBaulichenAnlage;
        }

        /**
         * Sets the value of the artDerBaulichenAnlage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage }
         *     
         */
        public void setArtDerBaulichenAnlage(Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage value) {
            this.artDerBaulichenAnlage = value;
        }

        /**
         * Gets the value of the bauvorhabenDatenblatt property.
         * 
         * @return
         *     possible object is
         *     {@link Datenblatt }
         *     
         */
        public Datenblatt getBauvorhabenDatenblatt() {
            return bauvorhabenDatenblatt;
        }

        /**
         * Sets the value of the bauvorhabenDatenblatt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Datenblatt }
         *     
         */
        public void setBauvorhabenDatenblatt(Datenblatt value) {
            this.bauvorhabenDatenblatt = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="artDesGebaeudes" type="{http://www.is-argebau.de/xbau/2}Code.BaulicheAnlagenGebaeude"/>
         *         &lt;element name="artDerSonstigenAnlage" type="{http://www.is-argebau.de/xbau/2}Code.BaulicheAnlagenSonstige"/>
         *         &lt;element name="artNichtAufgefuehrt" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "artDesGebaeudes",
            "artDerSonstigenAnlage",
            "artNichtAufgefuehrt"
        })
        public static class ArtDerBaulichenAnlage {

            protected CodeBaulicheAnlagenGebaeude artDesGebaeudes;
            protected CodeBaulicheAnlagenSonstige artDerSonstigenAnlage;
            protected String artNichtAufgefuehrt;

            /**
             * Gets the value of the artDesGebaeudes property.
             * 
             * @return
             *     possible object is
             *     {@link CodeBaulicheAnlagenGebaeude }
             *     
             */
            public CodeBaulicheAnlagenGebaeude getArtDesGebaeudes() {
                return artDesGebaeudes;
            }

            /**
             * Sets the value of the artDesGebaeudes property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeBaulicheAnlagenGebaeude }
             *     
             */
            public void setArtDesGebaeudes(CodeBaulicheAnlagenGebaeude value) {
                this.artDesGebaeudes = value;
            }

            /**
             * Gets the value of the artDerSonstigenAnlage property.
             * 
             * @return
             *     possible object is
             *     {@link CodeBaulicheAnlagenSonstige }
             *     
             */
            public CodeBaulicheAnlagenSonstige getArtDerSonstigenAnlage() {
                return artDerSonstigenAnlage;
            }

            /**
             * Sets the value of the artDerSonstigenAnlage property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeBaulicheAnlagenSonstige }
             *     
             */
            public void setArtDerSonstigenAnlage(CodeBaulicheAnlagenSonstige value) {
                this.artDerSonstigenAnlage = value;
            }

            /**
             * Gets the value of the artNichtAufgefuehrt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArtNichtAufgefuehrt() {
                return artNichtAufgefuehrt;
            }

            /**
             * Sets the value of the artNichtAufgefuehrt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArtNichtAufgefuehrt(String value) {
                this.artNichtAufgefuehrt = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="baugrundstueck" type="{http://www.is-argebau.de/xbau/2}Baugrundstueck" maxOccurs="unbounded"/>
     *         &lt;element name="lageBauvorhaben" type="{http://www.is-argebau.de/xbau/2}GeoreferenzierteLage" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "baugrundstueck",
        "lageBauvorhaben"
    })
    public static class Verortung {

        @XmlElement(required = true)
        protected List<Baugrundstueck> baugrundstueck;
        protected GeoreferenzierteLage lageBauvorhaben;

        /**
         * Gets the value of the baugrundstueck property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the baugrundstueck property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBaugrundstueck().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Baugrundstueck }
         * 
         * 
         */
        public List<Baugrundstueck> getBaugrundstueck() {
            if (baugrundstueck == null) {
                baugrundstueck = new ArrayList<Baugrundstueck>();
            }
            return this.baugrundstueck;
        }

        /**
         * Gets the value of the lageBauvorhaben property.
         * 
         * @return
         *     possible object is
         *     {@link GeoreferenzierteLage }
         *     
         */
        public GeoreferenzierteLage getLageBauvorhaben() {
            return lageBauvorhaben;
        }

        /**
         * Sets the value of the lageBauvorhaben property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeoreferenzierteLage }
         *     
         */
        public void setLageBauvorhaben(GeoreferenzierteLage value) {
            this.lageBauvorhaben = value;
        }

    }

}
