//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ beinhaltet die Befunde der formellen Prüfung eines Antrags oder einer Anfrage. Für jeden Befund sind die entsprechenden Parameter gefüllt, die Inhalt und Bezug des Befundes für den Antragsteller bzw. Anfragenden nachvollziehbar machen.
 * 
 * <p>Java class for BefundlisteFormell complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BefundlisteFormell">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="befund" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="artDesBefundes" type="{http://www.is-argebau.de/xbau/2}Code.FormelleBefundeArt"/>
 *                   &lt;element name="refAnlage" type="{http://www.is-argebau.de/xbau/2}RefAnlage" minOccurs="0"/>
 *                   &lt;element name="betroffeneAnlage" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauantragBearbeitung" minOccurs="0"/>
 *                   &lt;element name="beschreibung" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BefundlisteFormell", propOrder = {
    "befund"
})
public class BefundlisteFormell {

    @XmlElement(required = true)
    protected List<BefundlisteFormell.Befund> befund;

    /**
     * Gets the value of the befund property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the befund property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBefund().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BefundlisteFormell.Befund }
     * 
     * 
     */
    public List<BefundlisteFormell.Befund> getBefund() {
        if (befund == null) {
            befund = new ArrayList<BefundlisteFormell.Befund>();
        }
        return this.befund;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="artDesBefundes" type="{http://www.is-argebau.de/xbau/2}Code.FormelleBefundeArt"/>
     *         &lt;element name="refAnlage" type="{http://www.is-argebau.de/xbau/2}RefAnlage" minOccurs="0"/>
     *         &lt;element name="betroffeneAnlage" type="{http://www.is-argebau.de/xbau/2}Code.VorlagenBauantragBearbeitung" minOccurs="0"/>
     *         &lt;element name="beschreibung" type="{http://www.is-argebau.de/xbau/2}Text"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "artDesBefundes",
        "refAnlage",
        "betroffeneAnlage",
        "beschreibung"
    })
    public static class Befund {

        @XmlElement(required = true)
        protected CodeFormelleBefundeArt artDesBefundes;
        protected RefAnlage refAnlage;
        protected CodeVorlagenBauantragBearbeitung betroffeneAnlage;
        @XmlElement(required = true)
        protected Text beschreibung;

        /**
         * Gets the value of the artDesBefundes property.
         * 
         * @return
         *     possible object is
         *     {@link CodeFormelleBefundeArt }
         *     
         */
        public CodeFormelleBefundeArt getArtDesBefundes() {
            return artDesBefundes;
        }

        /**
         * Sets the value of the artDesBefundes property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeFormelleBefundeArt }
         *     
         */
        public void setArtDesBefundes(CodeFormelleBefundeArt value) {
            this.artDesBefundes = value;
        }

        /**
         * Gets the value of the refAnlage property.
         * 
         * @return
         *     possible object is
         *     {@link RefAnlage }
         *     
         */
        public RefAnlage getRefAnlage() {
            return refAnlage;
        }

        /**
         * Sets the value of the refAnlage property.
         * 
         * @param value
         *     allowed object is
         *     {@link RefAnlage }
         *     
         */
        public void setRefAnlage(RefAnlage value) {
            this.refAnlage = value;
        }

        /**
         * Gets the value of the betroffeneAnlage property.
         * 
         * @return
         *     possible object is
         *     {@link CodeVorlagenBauantragBearbeitung }
         *     
         */
        public CodeVorlagenBauantragBearbeitung getBetroffeneAnlage() {
            return betroffeneAnlage;
        }

        /**
         * Sets the value of the betroffeneAnlage property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeVorlagenBauantragBearbeitung }
         *     
         */
        public void setBetroffeneAnlage(CodeVorlagenBauantragBearbeitung value) {
            this.betroffeneAnlage = value;
        }

        /**
         * Gets the value of the beschreibung property.
         * 
         * @return
         *     possible object is
         *     {@link Text }
         *     
         */
        public Text getBeschreibung() {
            return beschreibung;
        }

        /**
         * Sets the value of the beschreibung property.
         * 
         * @param value
         *     allowed object is
         *     {@link Text }
         *     
         */
        public void setBeschreibung(Text value) {
            this.beschreibung = value;
        }

    }

}
