//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Eine Instanz diesen Typs steht für eine Befundliste der materiellen Prüfung eines Antrags. Jeder Befund beinhaltet die Parameter, die einen  belastenden Verwaltungsakt im Kontext eines Baugenehmigungsvorgangs definieren.
 * 
 * <p>Java class for BefundlistePruefungBauzustand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BefundlistePruefungBauzustand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="befund" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="beschreibung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *                   &lt;element name="verweise" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
 *                   &lt;element name="rechtsbereich" type="{http://www.is-argebau.de/xbau/2}Code.Rechtsbereich" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BefundlistePruefungBauzustand", propOrder = {
    "befund"
})
public class BefundlistePruefungBauzustand {

    @XmlElement(required = true)
    protected List<BefundlistePruefungBauzustand.Befund> befund;

    /**
     * Gets the value of the befund property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the befund property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBefund().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BefundlistePruefungBauzustand.Befund }
     * 
     * 
     */
    public List<BefundlistePruefungBauzustand.Befund> getBefund() {
        if (befund == null) {
            befund = new ArrayList<BefundlistePruefungBauzustand.Befund>();
        }
        return this.befund;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="beschreibung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
     *         &lt;element name="verweise" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
     *         &lt;element name="rechtsbereich" type="{http://www.is-argebau.de/xbau/2}Code.Rechtsbereich" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beschreibung",
        "verweise",
        "rechtsbereich"
    })
    public static class Befund {

        @XmlElement(required = true)
        protected String beschreibung;
        protected Text verweise;
        protected CodeRechtsbereich rechtsbereich;

        /**
         * Gets the value of the beschreibung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeschreibung() {
            return beschreibung;
        }

        /**
         * Sets the value of the beschreibung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeschreibung(String value) {
            this.beschreibung = value;
        }

        /**
         * Gets the value of the verweise property.
         * 
         * @return
         *     possible object is
         *     {@link Text }
         *     
         */
        public Text getVerweise() {
            return verweise;
        }

        /**
         * Sets the value of the verweise property.
         * 
         * @param value
         *     allowed object is
         *     {@link Text }
         *     
         */
        public void setVerweise(Text value) {
            this.verweise = value;
        }

        /**
         * Gets the value of the rechtsbereich property.
         * 
         * @return
         *     possible object is
         *     {@link CodeRechtsbereich }
         *     
         */
        public CodeRechtsbereich getRechtsbereich() {
            return rechtsbereich;
        }

        /**
         * Sets the value of the rechtsbereich property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeRechtsbereich }
         *     
         */
        public void setRechtsbereich(CodeRechtsbereich value) {
            this.rechtsbereich = value;
        }

    }

}
