//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ beinhaltet die Parameter eines Bescheides, den die Bauaufsichtsbehörde nach Prüfung eines Antrags erlässt.
 * 
 * <p>Java class for Bescheid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bescheid">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tenor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="istGenehmigung" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="kommentareFachrecht" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="kommentarFachrecht" type="{http://www.is-argebau.de/xbau/2}Text" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="abweichung" type="{http://www.is-argebau.de/xbau/2}AbweichungBearbeitet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nebenbestimmung" type="{http://www.is-argebau.de/xbau/2}Nebenbestimmung" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="begruendung" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
 *         &lt;element name="rechtshelfsbelehrung" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *         &lt;element name="hinweise" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bescheid", propOrder = {
    "tenor",
    "abweichung",
    "nebenbestimmung",
    "begruendung",
    "rechtshelfsbelehrung",
    "hinweise"
})
public class Bescheid {

    @XmlElement(required = true)
    protected Bescheid.Tenor tenor;
    protected List<AbweichungBearbeitet> abweichung;
    protected List<Nebenbestimmung> nebenbestimmung;
    protected Text begruendung;
    @XmlElement(required = true)
    protected Text rechtshelfsbelehrung;
    protected Text hinweise;

    /**
     * Gets the value of the tenor property.
     * 
     * @return
     *     possible object is
     *     {@link Bescheid.Tenor }
     *     
     */
    public Bescheid.Tenor getTenor() {
        return tenor;
    }

    /**
     * Sets the value of the tenor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bescheid.Tenor }
     *     
     */
    public void setTenor(Bescheid.Tenor value) {
        this.tenor = value;
    }

    /**
     * Gets the value of the abweichung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abweichung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbweichung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbweichungBearbeitet }
     * 
     * 
     */
    public List<AbweichungBearbeitet> getAbweichung() {
        if (abweichung == null) {
            abweichung = new ArrayList<AbweichungBearbeitet>();
        }
        return this.abweichung;
    }

    /**
     * Gets the value of the nebenbestimmung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nebenbestimmung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNebenbestimmung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Nebenbestimmung }
     * 
     * 
     */
    public List<Nebenbestimmung> getNebenbestimmung() {
        if (nebenbestimmung == null) {
            nebenbestimmung = new ArrayList<Nebenbestimmung>();
        }
        return this.nebenbestimmung;
    }

    /**
     * Gets the value of the begruendung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getBegruendung() {
        return begruendung;
    }

    /**
     * Sets the value of the begruendung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setBegruendung(Text value) {
        this.begruendung = value;
    }

    /**
     * Gets the value of the rechtshelfsbelehrung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getRechtshelfsbelehrung() {
        return rechtshelfsbelehrung;
    }

    /**
     * Sets the value of the rechtshelfsbelehrung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setRechtshelfsbelehrung(Text value) {
        this.rechtshelfsbelehrung = value;
    }

    /**
     * Gets the value of the hinweise property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getHinweise() {
        return hinweise;
    }

    /**
     * Sets the value of the hinweise property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setHinweise(Text value) {
        this.hinweise = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="istGenehmigung" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="kommentareFachrecht" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="kommentarFachrecht" type="{http://www.is-argebau.de/xbau/2}Text" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "istGenehmigung",
        "kommentareFachrecht"
    })
    public static class Tenor {

        protected boolean istGenehmigung;
        protected Bescheid.Tenor.KommentareFachrecht kommentareFachrecht;

        /**
         * Gets the value of the istGenehmigung property.
         * 
         */
        public boolean isIstGenehmigung() {
            return istGenehmigung;
        }

        /**
         * Sets the value of the istGenehmigung property.
         * 
         */
        public void setIstGenehmigung(boolean value) {
            this.istGenehmigung = value;
        }

        /**
         * Gets the value of the kommentareFachrecht property.
         * 
         * @return
         *     possible object is
         *     {@link Bescheid.Tenor.KommentareFachrecht }
         *     
         */
        public Bescheid.Tenor.KommentareFachrecht getKommentareFachrecht() {
            return kommentareFachrecht;
        }

        /**
         * Sets the value of the kommentareFachrecht property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bescheid.Tenor.KommentareFachrecht }
         *     
         */
        public void setKommentareFachrecht(Bescheid.Tenor.KommentareFachrecht value) {
            this.kommentareFachrecht = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="kommentarFachrecht" type="{http://www.is-argebau.de/xbau/2}Text" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "kommentarFachrecht"
        })
        public static class KommentareFachrecht {

            @XmlElement(required = true)
            protected List<Text> kommentarFachrecht;

            /**
             * Gets the value of the kommentarFachrecht property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the kommentarFachrecht property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKommentarFachrecht().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Text }
             * 
             * 
             */
            public List<Text> getKommentarFachrecht() {
                if (kommentarFachrecht == null) {
                    kommentarFachrecht = new ArrayList<Text>();
                }
                return this.kommentarFachrecht;
            }

        }

    }

}
