//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Typ für die an einem (sich in Planung befindlichen) Bauprojekt beteiligten Parteien (Personen und Organisationen).
 * 
 * <p>Java class for BeteiligteBauprojektInPlanung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeteiligteBauprojektInPlanung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bauherr" type="{http://www.is-argebau.de/xbau/2}Akteur" maxOccurs="unbounded"/>
 *         &lt;element name="bevollmaechtigter" type="{http://www.is-argebau.de/xbau/2}AmBauBeteiligtePerson" minOccurs="0"/>
 *         &lt;element name="grundstueckseigentuemer" type="{http://www.is-argebau.de/xbau/2}Akteur" minOccurs="0"/>
 *         &lt;element name="entwurfsverfasser" type="{http://www.is-argebau.de/xbau/2}Entwurfsverfasser"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeteiligteBauprojektInPlanung", propOrder = {
    "bauherr",
    "bevollmaechtigter",
    "grundstueckseigentuemer",
    "entwurfsverfasser"
})
public class BeteiligteBauprojektInPlanung {

    @XmlElement(required = true)
    protected List<Akteur> bauherr;
    protected AmBauBeteiligtePerson bevollmaechtigter;
    protected Akteur grundstueckseigentuemer;
    @XmlElement(required = true)
    protected Entwurfsverfasser entwurfsverfasser;

    /**
     * Gets the value of the bauherr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bauherr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBauherr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Akteur }
     * 
     * 
     */
    public List<Akteur> getBauherr() {
        if (bauherr == null) {
            bauherr = new ArrayList<Akteur>();
        }
        return this.bauherr;
    }

    /**
     * Gets the value of the bevollmaechtigter property.
     * 
     * @return
     *     possible object is
     *     {@link AmBauBeteiligtePerson }
     *     
     */
    public AmBauBeteiligtePerson getBevollmaechtigter() {
        return bevollmaechtigter;
    }

    /**
     * Sets the value of the bevollmaechtigter property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmBauBeteiligtePerson }
     *     
     */
    public void setBevollmaechtigter(AmBauBeteiligtePerson value) {
        this.bevollmaechtigter = value;
    }

    /**
     * Gets the value of the grundstueckseigentuemer property.
     * 
     * @return
     *     possible object is
     *     {@link Akteur }
     *     
     */
    public Akteur getGrundstueckseigentuemer() {
        return grundstueckseigentuemer;
    }

    /**
     * Sets the value of the grundstueckseigentuemer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Akteur }
     *     
     */
    public void setGrundstueckseigentuemer(Akteur value) {
        this.grundstueckseigentuemer = value;
    }

    /**
     * Gets the value of the entwurfsverfasser property.
     * 
     * @return
     *     possible object is
     *     {@link Entwurfsverfasser }
     *     
     */
    public Entwurfsverfasser getEntwurfsverfasser() {
        return entwurfsverfasser;
    }

    /**
     * Sets the value of the entwurfsverfasser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entwurfsverfasser }
     *     
     */
    public void setEntwurfsverfasser(Entwurfsverfasser value) {
        this.entwurfsverfasser = value;
    }

}
