//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Typ für die an der Umsetzung eines Bauprojekts beteiligten Parteien (Personen und Organisationen).
 * 
 * <p>Java class for BeteiligteBauprojektUmsetzung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeteiligteBauprojektUmsetzung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bauherr" type="{http://www.is-argebau.de/xbau/2}Akteur" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bauleiter" type="{http://www.is-argebau.de/xbau/2}Akteur"/>
 *         &lt;element name="fachbauleiter" type="{http://www.is-argebau.de/xbau/2}Akteur" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bauunternehmer" type="{http://www.is-argebau.de/xbau/2}Organisation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeteiligteBauprojektUmsetzung", propOrder = {
    "bauherr",
    "bauleiter",
    "fachbauleiter",
    "bauunternehmer"
})
public class BeteiligteBauprojektUmsetzung {

    protected List<Akteur> bauherr;
    @XmlElement(required = true)
    protected Akteur bauleiter;
    protected List<Akteur> fachbauleiter;
    @XmlElement(required = true)
    protected Organisation bauunternehmer;

    /**
     * Gets the value of the bauherr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bauherr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBauherr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Akteur }
     * 
     * 
     */
    public List<Akteur> getBauherr() {
        if (bauherr == null) {
            bauherr = new ArrayList<Akteur>();
        }
        return this.bauherr;
    }

    /**
     * Gets the value of the bauleiter property.
     * 
     * @return
     *     possible object is
     *     {@link Akteur }
     *     
     */
    public Akteur getBauleiter() {
        return bauleiter;
    }

    /**
     * Sets the value of the bauleiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Akteur }
     *     
     */
    public void setBauleiter(Akteur value) {
        this.bauleiter = value;
    }

    /**
     * Gets the value of the fachbauleiter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fachbauleiter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFachbauleiter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Akteur }
     * 
     * 
     */
    public List<Akteur> getFachbauleiter() {
        if (fachbauleiter == null) {
            fachbauleiter = new ArrayList<Akteur>();
        }
        return this.fachbauleiter;
    }

    /**
     * Gets the value of the bauunternehmer property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation }
     *     
     */
    public Organisation getBauunternehmer() {
        return bauunternehmer;
    }

    /**
     * Sets the value of the bauunternehmer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation }
     *     
     */
    public void setBauunternehmer(Organisation value) {
        this.bauunternehmer = value;
    }

}
