//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ gestattet Eintragungen, um auf einen Vorgang (Geschäftsprozess) und ggf. auf eine Nachricht, die im Rahmen dieses Vorgangs gesendet worden ist, Bezug zu nehmen.
 * 
 * <p>Java class for Bezug complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bezug">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vorgang" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *         &lt;element name="bezugNachricht" type="{http://www.is-argebau.de/xbau/2}Identifikation.Nachricht" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bezug", propOrder = {
    "vorgang",
    "bezugNachricht"
})
public class Bezug {

    @XmlElement(required = true)
    protected String vorgang;
    protected IdentifikationNachricht bezugNachricht;

    /**
     * Gets the value of the vorgang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorgang() {
        return vorgang;
    }

    /**
     * Sets the value of the vorgang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorgang(String value) {
        this.vorgang = value;
    }

    /**
     * Gets the value of the bezugNachricht property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikationNachricht }
     *     
     */
    public IdentifikationNachricht getBezugNachricht() {
        return bezugNachricht;
    }

    /**
     * Sets the value of the bezugNachricht property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikationNachricht }
     *     
     */
    public void setBezugNachricht(IdentifikationNachricht value) {
        this.bezugNachricht = value;
    }

}
