//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ dient zur Zusammenstellung von technischen Daten und Kennzahlen zum Bauvorahben.
 * 
 * <p>Java class for Datenblatt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Datenblatt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bauordnungsrechtlicheKlassifikation" type="{http://www.is-argebau.de/xbau/2}BauordnungsrechtlicheKlassifikation" minOccurs="0"/>
 *         &lt;element name="baulicheNutzungMass" type="{http://www.is-argebau.de/xbau/2}BaulicheNutzungMass" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bauweise" type="{http://www.is-argebau.de/xbau/2}Code.Bauweise" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datenblatt", propOrder = {
    "bauordnungsrechtlicheKlassifikation",
    "baulicheNutzungMass",
    "bauweise"
})
public class Datenblatt {

    protected BauordnungsrechtlicheKlassifikation bauordnungsrechtlicheKlassifikation;
    protected List<BaulicheNutzungMass> baulicheNutzungMass;
    protected CodeBauweise bauweise;

    /**
     * Gets the value of the bauordnungsrechtlicheKlassifikation property.
     * 
     * @return
     *     possible object is
     *     {@link BauordnungsrechtlicheKlassifikation }
     *     
     */
    public BauordnungsrechtlicheKlassifikation getBauordnungsrechtlicheKlassifikation() {
        return bauordnungsrechtlicheKlassifikation;
    }

    /**
     * Sets the value of the bauordnungsrechtlicheKlassifikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BauordnungsrechtlicheKlassifikation }
     *     
     */
    public void setBauordnungsrechtlicheKlassifikation(BauordnungsrechtlicheKlassifikation value) {
        this.bauordnungsrechtlicheKlassifikation = value;
    }

    /**
     * Gets the value of the baulicheNutzungMass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baulicheNutzungMass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaulicheNutzungMass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaulicheNutzungMass }
     * 
     * 
     */
    public List<BaulicheNutzungMass> getBaulicheNutzungMass() {
        if (baulicheNutzungMass == null) {
            baulicheNutzungMass = new ArrayList<BaulicheNutzungMass>();
        }
        return this.baulicheNutzungMass;
    }

    /**
     * Gets the value of the bauweise property.
     * 
     * @return
     *     possible object is
     *     {@link CodeBauweise }
     *     
     */
    public CodeBauweise getBauweise() {
        return bauweise;
    }

    /**
     * Sets the value of the bauweise property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeBauweise }
     *     
     */
    public void setBauweise(CodeBauweise value) {
        this.bauweise = value;
    }

}
