//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ dient dazu, die Daten des  Entwurfsverfassers zu übermitteln, der verantwortlich an der Vorbereitung des  Bauprojekts mitwirkt bzw. mitgewirkt hat.
 * 
 * <p>Java class for Entwurfsverfasser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entwurfsverfasser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personendaten" type="{http://www.is-argebau.de/xbau/2}AmBauBeteiligtePerson" minOccurs="0"/>
 *         &lt;element name="bauvorlageberechtigung" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="sachverhalt" type="{http://www.is-argebau.de/xbau/2}Code.BauvorlageberechtigungSachverhalt"/>
 *                   &lt;element name="kammer" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nummerEintragungsliste" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entwurfsverfasser", propOrder = {
    "personendaten",
    "bauvorlageberechtigung"
})
public class Entwurfsverfasser {

    protected AmBauBeteiligtePerson personendaten;
    protected Entwurfsverfasser.Bauvorlageberechtigung bauvorlageberechtigung;

    /**
     * Gets the value of the personendaten property.
     * 
     * @return
     *     possible object is
     *     {@link AmBauBeteiligtePerson }
     *     
     */
    public AmBauBeteiligtePerson getPersonendaten() {
        return personendaten;
    }

    /**
     * Sets the value of the personendaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmBauBeteiligtePerson }
     *     
     */
    public void setPersonendaten(AmBauBeteiligtePerson value) {
        this.personendaten = value;
    }

    /**
     * Gets the value of the bauvorlageberechtigung property.
     * 
     * @return
     *     possible object is
     *     {@link Entwurfsverfasser.Bauvorlageberechtigung }
     *     
     */
    public Entwurfsverfasser.Bauvorlageberechtigung getBauvorlageberechtigung() {
        return bauvorlageberechtigung;
    }

    /**
     * Sets the value of the bauvorlageberechtigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entwurfsverfasser.Bauvorlageberechtigung }
     *     
     */
    public void setBauvorlageberechtigung(Entwurfsverfasser.Bauvorlageberechtigung value) {
        this.bauvorlageberechtigung = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="sachverhalt" type="{http://www.is-argebau.de/xbau/2}Code.BauvorlageberechtigungSachverhalt"/>
     *         &lt;element name="kammer" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nummerEintragungsliste" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sachverhalt",
        "kammer"
    })
    public static class Bauvorlageberechtigung {

        protected CodeBauvorlageberechtigungSachverhalt sachverhalt;
        protected Entwurfsverfasser.Bauvorlageberechtigung.Kammer kammer;

        /**
         * Gets the value of the sachverhalt property.
         * 
         * @return
         *     possible object is
         *     {@link CodeBauvorlageberechtigungSachverhalt }
         *     
         */
        public CodeBauvorlageberechtigungSachverhalt getSachverhalt() {
            return sachverhalt;
        }

        /**
         * Sets the value of the sachverhalt property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeBauvorlageberechtigungSachverhalt }
         *     
         */
        public void setSachverhalt(CodeBauvorlageberechtigungSachverhalt value) {
            this.sachverhalt = value;
        }

        /**
         * Gets the value of the kammer property.
         * 
         * @return
         *     possible object is
         *     {@link Entwurfsverfasser.Bauvorlageberechtigung.Kammer }
         *     
         */
        public Entwurfsverfasser.Bauvorlageberechtigung.Kammer getKammer() {
            return kammer;
        }

        /**
         * Sets the value of the kammer property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entwurfsverfasser.Bauvorlageberechtigung.Kammer }
         *     
         */
        public void setKammer(Entwurfsverfasser.Bauvorlageberechtigung.Kammer value) {
            this.kammer = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nummerEintragungsliste" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nummerEintragungsliste"
        })
        public static class Kammer {

            @XmlElement(required = true)
            protected String nummerEintragungsliste;

            /**
             * Gets the value of the nummerEintragungsliste property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNummerEintragungsliste() {
                return nummerEintragungsliste;
            }

            /**
             * Sets the value of the nummerEintragungsliste property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNummerEintragungsliste(String value) {
                this.nummerEintragungsliste = value;
            }

        }

    }

}
