//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ beinhaltet die Parameter einer beantragten Erleichterung, die der Bauaufsichtsbehörde zur Genehmigung vorgelegt werden soll.
 * 
 * <p>Java class for ErleichterungAngefragt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErleichterungAngefragt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gegenstand" type="{http://www.is-argebau.de/xbau/2}Code.ErleichterungGegenstand"/>
 *         &lt;element name="beschreibung" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *         &lt;element name="begruendung" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErleichterungAngefragt", propOrder = {
    "gegenstand",
    "beschreibung",
    "begruendung"
})
public class ErleichterungAngefragt {

    @XmlElement(required = true)
    protected CodeErleichterungGegenstand gegenstand;
    @XmlElement(required = true)
    protected Text beschreibung;
    protected Text begruendung;

    /**
     * Gets the value of the gegenstand property.
     * 
     * @return
     *     possible object is
     *     {@link CodeErleichterungGegenstand }
     *     
     */
    public CodeErleichterungGegenstand getGegenstand() {
        return gegenstand;
    }

    /**
     * Sets the value of the gegenstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeErleichterungGegenstand }
     *     
     */
    public void setGegenstand(CodeErleichterungGegenstand value) {
        this.gegenstand = value;
    }

    /**
     * Gets the value of the beschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getBeschreibung() {
        return beschreibung;
    }

    /**
     * Sets the value of the beschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setBeschreibung(Text value) {
        this.beschreibung = value;
    }

    /**
     * Gets the value of the begruendung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getBegruendung() {
        return begruendung;
    }

    /**
     * Sets the value of the begruendung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setBegruendung(Text value) {
        this.begruendung = value;
    }

}
