//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Typ zur eindeutigen Identifikation eines Flurstücks.
 * Ein Flurstück ist ein amtlich vermessener Teil der Erdoberfläche. Das Liegenschaftskataster ordnet jedem Flurstück des jeweiligen Nummerierungsbezirks (Flur oder Gemarkung) eine Flurstücksnummer zu.
 * 
 * <p>Java class for FlurstueckKennzeichnung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlurstueckKennzeichnung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bundesland" type="{http://www.is-argebau.de/xbau/2}Code.Bundesland"/>
 *         &lt;element name="flurstueck" type="{http://www.is-argebau.de/xbau/2}Geokodierung"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlurstueckKennzeichnung", propOrder = {
    "bundesland",
    "flurstueck"
})
public class FlurstueckKennzeichnung {

    @XmlElement(required = true)
    protected CodeBundesland bundesland;
    @XmlElement(required = true)
    protected Geokodierung flurstueck;

    /**
     * Gets the value of the bundesland property.
     * 
     * @return
     *     possible object is
     *     {@link CodeBundesland }
     *     
     */
    public CodeBundesland getBundesland() {
        return bundesland;
    }

    /**
     * Sets the value of the bundesland property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeBundesland }
     *     
     */
    public void setBundesland(CodeBundesland value) {
        this.bundesland = value;
    }

    /**
     * Gets the value of the flurstueck property.
     * 
     * @return
     *     possible object is
     *     {@link Geokodierung }
     *     
     */
    public Geokodierung getFlurstueck() {
        return flurstueck;
    }

    /**
     * Sets the value of the flurstueck property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geokodierung }
     *     
     */
    public void setFlurstueck(Geokodierung value) {
        this.flurstueck = value;
    }

}
