//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ beinhaltet die Parameter eines Gebührenbescheids der Bauaufsichtsbehörde. Es sind die Daten zu Gegenstand, Herleitung, Betrag und Bezahlung der Gebühren enthalten.
 * 
 * <p>Java class for Gebuehrenbescheid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gebuehrenbescheid">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="istVorauszahlungsbescheid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="begruendung" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *         &lt;element name="kostenberechnung" type="{http://www.is-argebau.de/xbau/2}Kostenberechnung" minOccurs="0"/>
 *         &lt;element name="zahlungsdaten" type="{http://www.is-argebau.de/xbau/2}Zahlungsdaten" minOccurs="0"/>
 *         &lt;element name="rechtshelfsbelehrung" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *         &lt;element name="informationVerspaetungszuschlag" type="{http://www.is-argebau.de/xbau/2}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gebuehrenbescheid", propOrder = {
    "istVorauszahlungsbescheid",
    "begruendung",
    "kostenberechnung",
    "zahlungsdaten",
    "rechtshelfsbelehrung",
    "informationVerspaetungszuschlag"
})
public class Gebuehrenbescheid {

    protected boolean istVorauszahlungsbescheid;
    @XmlElement(required = true)
    protected Text begruendung;
    protected Kostenberechnung kostenberechnung;
    protected Zahlungsdaten zahlungsdaten;
    @XmlElement(required = true)
    protected Text rechtshelfsbelehrung;
    protected Text informationVerspaetungszuschlag;

    /**
     * Gets the value of the istVorauszahlungsbescheid property.
     * 
     */
    public boolean isIstVorauszahlungsbescheid() {
        return istVorauszahlungsbescheid;
    }

    /**
     * Sets the value of the istVorauszahlungsbescheid property.
     * 
     */
    public void setIstVorauszahlungsbescheid(boolean value) {
        this.istVorauszahlungsbescheid = value;
    }

    /**
     * Gets the value of the begruendung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getBegruendung() {
        return begruendung;
    }

    /**
     * Sets the value of the begruendung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setBegruendung(Text value) {
        this.begruendung = value;
    }

    /**
     * Gets the value of the kostenberechnung property.
     * 
     * @return
     *     possible object is
     *     {@link Kostenberechnung }
     *     
     */
    public Kostenberechnung getKostenberechnung() {
        return kostenberechnung;
    }

    /**
     * Sets the value of the kostenberechnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kostenberechnung }
     *     
     */
    public void setKostenberechnung(Kostenberechnung value) {
        this.kostenberechnung = value;
    }

    /**
     * Gets the value of the zahlungsdaten property.
     * 
     * @return
     *     possible object is
     *     {@link Zahlungsdaten }
     *     
     */
    public Zahlungsdaten getZahlungsdaten() {
        return zahlungsdaten;
    }

    /**
     * Sets the value of the zahlungsdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zahlungsdaten }
     *     
     */
    public void setZahlungsdaten(Zahlungsdaten value) {
        this.zahlungsdaten = value;
    }

    /**
     * Gets the value of the rechtshelfsbelehrung property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getRechtshelfsbelehrung() {
        return rechtshelfsbelehrung;
    }

    /**
     * Sets the value of the rechtshelfsbelehrung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setRechtshelfsbelehrung(Text value) {
        this.rechtshelfsbelehrung = value;
    }

    /**
     * Gets the value of the informationVerspaetungszuschlag property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getInformationVerspaetungszuschlag() {
        return informationVerspaetungszuschlag;
    }

    /**
     * Sets the value of the informationVerspaetungszuschlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setInformationVerspaetungszuschlag(Text value) {
        this.informationVerspaetungszuschlag = value;
    }

}
