//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ fasst Angaben zu den Grundstücksflächen des Vorhabens zusammen.
 * 
 * <p>Java class for Grundstuecksflaechen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grundstuecksflaechen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bebauteGrundstuecksflaeche" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="nichtBebauteGrundstuecksflaeche" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="versiegelteFlaeche" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="spielUndFreizeitflaeche" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="flaecheDerNebenanlagen" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="flaecheDerGemeinschaftsanlagen" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="stellplaetzeUndDerenZufahrten" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grundstuecksflaechen", propOrder = {
    "bebauteGrundstuecksflaeche",
    "nichtBebauteGrundstuecksflaeche",
    "versiegelteFlaeche",
    "spielUndFreizeitflaeche",
    "flaecheDerNebenanlagen",
    "flaecheDerGemeinschaftsanlagen",
    "stellplaetzeUndDerenZufahrten"
})
public class Grundstuecksflaechen {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger bebauteGrundstuecksflaeche;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger nichtBebauteGrundstuecksflaeche;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger versiegelteFlaeche;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger spielUndFreizeitflaeche;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger flaecheDerNebenanlagen;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger flaecheDerGemeinschaftsanlagen;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger stellplaetzeUndDerenZufahrten;

    /**
     * Gets the value of the bebauteGrundstuecksflaeche property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBebauteGrundstuecksflaeche() {
        return bebauteGrundstuecksflaeche;
    }

    /**
     * Sets the value of the bebauteGrundstuecksflaeche property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBebauteGrundstuecksflaeche(BigInteger value) {
        this.bebauteGrundstuecksflaeche = value;
    }

    /**
     * Gets the value of the nichtBebauteGrundstuecksflaeche property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNichtBebauteGrundstuecksflaeche() {
        return nichtBebauteGrundstuecksflaeche;
    }

    /**
     * Sets the value of the nichtBebauteGrundstuecksflaeche property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNichtBebauteGrundstuecksflaeche(BigInteger value) {
        this.nichtBebauteGrundstuecksflaeche = value;
    }

    /**
     * Gets the value of the versiegelteFlaeche property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersiegelteFlaeche() {
        return versiegelteFlaeche;
    }

    /**
     * Sets the value of the versiegelteFlaeche property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersiegelteFlaeche(BigInteger value) {
        this.versiegelteFlaeche = value;
    }

    /**
     * Gets the value of the spielUndFreizeitflaeche property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpielUndFreizeitflaeche() {
        return spielUndFreizeitflaeche;
    }

    /**
     * Sets the value of the spielUndFreizeitflaeche property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpielUndFreizeitflaeche(BigInteger value) {
        this.spielUndFreizeitflaeche = value;
    }

    /**
     * Gets the value of the flaecheDerNebenanlagen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlaecheDerNebenanlagen() {
        return flaecheDerNebenanlagen;
    }

    /**
     * Sets the value of the flaecheDerNebenanlagen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlaecheDerNebenanlagen(BigInteger value) {
        this.flaecheDerNebenanlagen = value;
    }

    /**
     * Gets the value of the flaecheDerGemeinschaftsanlagen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlaecheDerGemeinschaftsanlagen() {
        return flaecheDerGemeinschaftsanlagen;
    }

    /**
     * Sets the value of the flaecheDerGemeinschaftsanlagen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlaecheDerGemeinschaftsanlagen(BigInteger value) {
        this.flaecheDerGemeinschaftsanlagen = value;
    }

    /**
     * Gets the value of the stellplaetzeUndDerenZufahrten property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStellplaetzeUndDerenZufahrten() {
        return stellplaetzeUndDerenZufahrten;
    }

    /**
     * Sets the value of the stellplaetzeUndDerenZufahrten property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStellplaetzeUndDerenZufahrten(BigInteger value) {
        this.stellplaetzeUndDerenZufahrten = value;
    }

}
