//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * [nd]
 * 
 * <p>Java class for Kostenberechnung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Kostenberechnung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gebuehrenposition" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="gebuehrenordnung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *                   &lt;element name="gebuehrentatbestand" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *                   &lt;element name="position" type="{http://www.is-argebau.de/xbau/2}Position"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="auslagenposition" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="position" type="{http://www.is-argebau.de/xbau/2}Position"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="summe" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kostenberechnung", propOrder = {
    "gebuehrenposition",
    "auslagenposition",
    "summe"
})
public class Kostenberechnung {

    protected List<Kostenberechnung.Gebuehrenposition> gebuehrenposition;
    protected List<Kostenberechnung.Auslagenposition> auslagenposition;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger summe;

    /**
     * Gets the value of the gebuehrenposition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gebuehrenposition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGebuehrenposition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kostenberechnung.Gebuehrenposition }
     * 
     * 
     */
    public List<Kostenberechnung.Gebuehrenposition> getGebuehrenposition() {
        if (gebuehrenposition == null) {
            gebuehrenposition = new ArrayList<Kostenberechnung.Gebuehrenposition>();
        }
        return this.gebuehrenposition;
    }

    /**
     * Gets the value of the auslagenposition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auslagenposition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuslagenposition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kostenberechnung.Auslagenposition }
     * 
     * 
     */
    public List<Kostenberechnung.Auslagenposition> getAuslagenposition() {
        if (auslagenposition == null) {
            auslagenposition = new ArrayList<Kostenberechnung.Auslagenposition>();
        }
        return this.auslagenposition;
    }

    /**
     * Gets the value of the summe property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSumme() {
        return summe;
    }

    /**
     * Sets the value of the summe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSumme(BigInteger value) {
        this.summe = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="position" type="{http://www.is-argebau.de/xbau/2}Position"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "position"
    })
    public static class Auslagenposition {

        @XmlElement(required = true)
        protected Position position;

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link Position }
         *     
         */
        public Position getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link Position }
         *     
         */
        public void setPosition(Position value) {
            this.position = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="gebuehrenordnung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
     *         &lt;element name="gebuehrentatbestand" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
     *         &lt;element name="position" type="{http://www.is-argebau.de/xbau/2}Position"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gebuehrenordnung",
        "gebuehrentatbestand",
        "position"
    })
    public static class Gebuehrenposition {

        @XmlElement(required = true)
        protected String gebuehrenordnung;
        @XmlElement(required = true)
        protected String gebuehrentatbestand;
        @XmlElement(required = true)
        protected Position position;

        /**
         * Gets the value of the gebuehrenordnung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGebuehrenordnung() {
            return gebuehrenordnung;
        }

        /**
         * Sets the value of the gebuehrenordnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGebuehrenordnung(String value) {
            this.gebuehrenordnung = value;
        }

        /**
         * Gets the value of the gebuehrentatbestand property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGebuehrentatbestand() {
            return gebuehrentatbestand;
        }

        /**
         * Sets the value of the gebuehrentatbestand property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGebuehrentatbestand(String value) {
            this.gebuehrentatbestand = value;
        }

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link Position }
         *     
         */
        public Position getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link Position }
         *     
         */
        public void setPosition(Position value) {
            this.position = value;
        }

    }

}
