//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.osci.xinneres.behoerde._3.BehoerdeErreichbar;


/**
 * Nachrichtenkopf für Nachrichten von Behörden an Private.
 * 
 * <p>Java class for Nachrichtenkopf.G2privat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Nachrichtenkopf.G2privat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifikation.nachricht" type="{http://www.is-argebau.de/xbau/2}Identifikation.Nachricht" form="unqualified"/>
 *         &lt;element name="leser" type="{http://www.is-argebau.de/xbau/2}Akteur" form="unqualified"/>
 *         &lt;element name="autor" type="{http://www.osci.de/xinneres/behoerde/3}Behoerde.Erreichbar" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nachrichtenkopf.G2privat", propOrder = {
    "identifikationNachricht",
    "leser",
    "autor"
})
public class NachrichtenkopfG2Privat {

    @XmlElement(name = "identifikation.nachricht", namespace = "", required = true)
    protected IdentifikationNachricht identifikationNachricht;
    @XmlElement(namespace = "", required = true)
    protected Akteur leser;
    @XmlElement(namespace = "", required = true)
    protected BehoerdeErreichbar autor;

    /**
     * Gets the value of the identifikationNachricht property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikationNachricht }
     *     
     */
    public IdentifikationNachricht getIdentifikationNachricht() {
        return identifikationNachricht;
    }

    /**
     * Sets the value of the identifikationNachricht property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikationNachricht }
     *     
     */
    public void setIdentifikationNachricht(IdentifikationNachricht value) {
        this.identifikationNachricht = value;
    }

    /**
     * Gets the value of the leser property.
     * 
     * @return
     *     possible object is
     *     {@link Akteur }
     *     
     */
    public Akteur getLeser() {
        return leser;
    }

    /**
     * Sets the value of the leser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Akteur }
     *     
     */
    public void setLeser(Akteur value) {
        this.leser = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link BehoerdeErreichbar }
     *     
     */
    public BehoerdeErreichbar getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehoerdeErreichbar }
     *     
     */
    public void setAutor(BehoerdeErreichbar value) {
        this.autor = value;
    }

}
