//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ fasst Angaben zu den Nutzungseinheiten des Vorhabens zusammen.
 * 
 * <p>Java class for Nutzungseinheiten complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Nutzungseinheiten">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wohneinheitenGesamt" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="wohneinheitenEigentumswohnungen" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="wohneinheitenMietwohnungen" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="wohneinheitenSozialwohnungen" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="wohnungenGewerblich" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="wohnungenFreiberuflich" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="nutzungseinheitenGewerbe" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nutzungseinheiten", propOrder = {
    "wohneinheitenGesamt",
    "wohneinheitenEigentumswohnungen",
    "wohneinheitenMietwohnungen",
    "wohneinheitenSozialwohnungen",
    "wohnungenGewerblich",
    "wohnungenFreiberuflich",
    "nutzungseinheitenGewerbe"
})
public class Nutzungseinheiten {

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger wohneinheitenGesamt;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger wohneinheitenEigentumswohnungen;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger wohneinheitenMietwohnungen;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger wohneinheitenSozialwohnungen;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger wohnungenGewerblich;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger wohnungenFreiberuflich;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger nutzungseinheitenGewerbe;

    /**
     * Gets the value of the wohneinheitenGesamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWohneinheitenGesamt() {
        return wohneinheitenGesamt;
    }

    /**
     * Sets the value of the wohneinheitenGesamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWohneinheitenGesamt(BigInteger value) {
        this.wohneinheitenGesamt = value;
    }

    /**
     * Gets the value of the wohneinheitenEigentumswohnungen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWohneinheitenEigentumswohnungen() {
        return wohneinheitenEigentumswohnungen;
    }

    /**
     * Sets the value of the wohneinheitenEigentumswohnungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWohneinheitenEigentumswohnungen(BigInteger value) {
        this.wohneinheitenEigentumswohnungen = value;
    }

    /**
     * Gets the value of the wohneinheitenMietwohnungen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWohneinheitenMietwohnungen() {
        return wohneinheitenMietwohnungen;
    }

    /**
     * Sets the value of the wohneinheitenMietwohnungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWohneinheitenMietwohnungen(BigInteger value) {
        this.wohneinheitenMietwohnungen = value;
    }

    /**
     * Gets the value of the wohneinheitenSozialwohnungen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWohneinheitenSozialwohnungen() {
        return wohneinheitenSozialwohnungen;
    }

    /**
     * Sets the value of the wohneinheitenSozialwohnungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWohneinheitenSozialwohnungen(BigInteger value) {
        this.wohneinheitenSozialwohnungen = value;
    }

    /**
     * Gets the value of the wohnungenGewerblich property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWohnungenGewerblich() {
        return wohnungenGewerblich;
    }

    /**
     * Sets the value of the wohnungenGewerblich property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWohnungenGewerblich(BigInteger value) {
        this.wohnungenGewerblich = value;
    }

    /**
     * Gets the value of the wohnungenFreiberuflich property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWohnungenFreiberuflich() {
        return wohnungenFreiberuflich;
    }

    /**
     * Sets the value of the wohnungenFreiberuflich property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWohnungenFreiberuflich(BigInteger value) {
        this.wohnungenFreiberuflich = value;
    }

    /**
     * Gets the value of the nutzungseinheitenGewerbe property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNutzungseinheitenGewerbe() {
        return nutzungseinheitenGewerbe;
    }

    /**
     * Sets the value of the nutzungseinheitenGewerbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNutzungseinheitenGewerbe(BigInteger value) {
        this.nutzungseinheitenGewerbe = value;
    }

}
