//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.is_argebau.xbau._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.is_argebau.xbau._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Kostenberechnung }
     * 
     */
    public Kostenberechnung createKostenberechnung() {
        return new Kostenberechnung();
    }

    /**
     * Create an instance of {@link Entwurfsverfasser }
     * 
     */
    public Entwurfsverfasser createEntwurfsverfasser() {
        return new Entwurfsverfasser();
    }

    /**
     * Create an instance of {@link Entwurfsverfasser.Bauvorlageberechtigung }
     * 
     */
    public Entwurfsverfasser.Bauvorlageberechtigung createEntwurfsverfasserBauvorlageberechtigung() {
        return new Entwurfsverfasser.Bauvorlageberechtigung();
    }

    /**
     * Create an instance of {@link AnlageBauvorlage }
     * 
     */
    public AnlageBauvorlage createAnlageBauvorlage() {
        return new AnlageBauvorlage();
    }

    /**
     * Create an instance of {@link BefundlistePruefungBauzustand }
     * 
     */
    public BefundlistePruefungBauzustand createBefundlistePruefungBauzustand() {
        return new BefundlistePruefungBauzustand();
    }

    /**
     * Create an instance of {@link GeoreferenzierteLage }
     * 
     */
    public GeoreferenzierteLage createGeoreferenzierteLage() {
        return new GeoreferenzierteLage();
    }

    /**
     * Create an instance of {@link BefundlisteFormell }
     * 
     */
    public BefundlisteFormell createBefundlisteFormell() {
        return new BefundlisteFormell();
    }

    /**
     * Create an instance of {@link Bescheid }
     * 
     */
    public Bescheid createBescheid() {
        return new Bescheid();
    }

    /**
     * Create an instance of {@link Bescheid.Tenor }
     * 
     */
    public Bescheid.Tenor createBescheidTenor() {
        return new Bescheid.Tenor();
    }

    /**
     * Create an instance of {@link BefundlisteMateriell }
     * 
     */
    public BefundlisteMateriell createBefundlisteMateriell() {
        return new BefundlisteMateriell();
    }

    /**
     * Create an instance of {@link BaulastErklaerung }
     * 
     */
    public BaulastErklaerung createBaulastErklaerung() {
        return new BaulastErklaerung();
    }

    /**
     * Create an instance of {@link Bauvorhaben }
     * 
     */
    public Bauvorhaben createBauvorhaben() {
        return new Bauvorhaben();
    }

    /**
     * Create an instance of {@link Bauvorhaben.Gegenstand }
     * 
     */
    public Bauvorhaben.Gegenstand createBauvorhabenGegenstand() {
        return new Bauvorhaben.Gegenstand();
    }

    /**
     * Create an instance of {@link BaugenehmigungGebuehrenbescheid0206 }
     * 
     */
    public BaugenehmigungGebuehrenbescheid0206 createBaugenehmigungGebuehrenbescheid0206() {
        return new BaugenehmigungGebuehrenbescheid0206();
    }

    /**
     * Create an instance of {@link NachrichtG2Privat }
     * 
     */
    public NachrichtG2Privat createNachrichtG2Privat() {
        return new NachrichtG2Privat();
    }

    /**
     * Create an instance of {@link NachrichtenkopfG2Privat }
     * 
     */
    public NachrichtenkopfG2Privat createNachrichtenkopfG2Privat() {
        return new NachrichtenkopfG2Privat();
    }

    /**
     * Create an instance of {@link Bezug }
     * 
     */
    public Bezug createBezug() {
        return new Bezug();
    }

    /**
     * Create an instance of {@link Gebuehrenbescheid }
     * 
     */
    public Gebuehrenbescheid createGebuehrenbescheid() {
        return new Gebuehrenbescheid();
    }

    /**
     * Create an instance of {@link BaugenehmigungAntrag0200 }
     * 
     */
    public BaugenehmigungAntrag0200 createBaugenehmigungAntrag0200() {
        return new BaugenehmigungAntrag0200();
    }

    /**
     * Create an instance of {@link NachrichtPrivat2G }
     * 
     */
    public NachrichtPrivat2G createNachrichtPrivat2G() {
        return new NachrichtPrivat2G();
    }

    /**
     * Create an instance of {@link NachrichtenkopfPrivat2G }
     * 
     */
    public NachrichtenkopfPrivat2G createNachrichtenkopfPrivat2G() {
        return new NachrichtenkopfPrivat2G();
    }

    /**
     * Create an instance of {@link AbweichungBeantragt }
     * 
     */
    public AbweichungBeantragt createAbweichungBeantragt() {
        return new AbweichungBeantragt();
    }

    /**
     * Create an instance of {@link ErleichterungAngefragt }
     * 
     */
    public ErleichterungAngefragt createErleichterungAngefragt() {
        return new ErleichterungAngefragt();
    }

    /**
     * Create an instance of {@link Anlagen }
     * 
     */
    public Anlagen createAnlagen() {
        return new Anlagen();
    }

    /**
     * Create an instance of {@link BaugenehmigungAnhoerung0203 }
     * 
     */
    public BaugenehmigungAnhoerung0203 createBaugenehmigungAnhoerung0203() {
        return new BaugenehmigungAnhoerung0203();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link BaugenehmigungAntragKorrektur0202 }
     * 
     */
    public BaugenehmigungAntragKorrektur0202 createBaugenehmigungAntragKorrektur0202() {
        return new BaugenehmigungAntragKorrektur0202();
    }

    /**
     * Create an instance of {@link BaugenehmigungBescheid0205 }
     * 
     */
    public BaugenehmigungBescheid0205 createBaugenehmigungBescheid0205() {
        return new BaugenehmigungBescheid0205();
    }

    /**
     * Create an instance of {@link BaugenehmigungStellungnahme0204 }
     * 
     */
    public BaugenehmigungStellungnahme0204 createBaugenehmigungStellungnahme0204() {
        return new BaugenehmigungStellungnahme0204();
    }

    /**
     * Create an instance of {@link StellungnahmeBelastenderVerwaltungsakt }
     * 
     */
    public StellungnahmeBelastenderVerwaltungsakt createStellungnahmeBelastenderVerwaltungsakt() {
        return new StellungnahmeBelastenderVerwaltungsakt();
    }

    /**
     * Create an instance of {@link BaugenehmigungFormellePruefung0201 }
     * 
     */
    public BaugenehmigungFormellePruefung0201 createBaugenehmigungFormellePruefung0201() {
        return new BaugenehmigungFormellePruefung0201();
    }

    /**
     * Create an instance of {@link CodeSonderbauten }
     * 
     */
    public CodeSonderbauten createCodeSonderbauten() {
        return new CodeSonderbauten();
    }

    /**
     * Create an instance of {@link BaulicheNutzungMass }
     * 
     */
    public BaulicheNutzungMass createBaulicheNutzungMass() {
        return new BaulicheNutzungMass();
    }

    /**
     * Create an instance of {@link CodeRechtsbereich }
     * 
     */
    public CodeRechtsbereich createCodeRechtsbereich() {
        return new CodeRechtsbereich();
    }

    /**
     * Create an instance of {@link CodeBeteiligungRolle }
     * 
     */
    public CodeBeteiligungRolle createCodeBeteiligungRolle() {
        return new CodeBeteiligungRolle();
    }

    /**
     * Create an instance of {@link CodeGebaeudeklasse }
     * 
     */
    public CodeGebaeudeklasse createCodeGebaeudeklasse() {
        return new CodeGebaeudeklasse();
    }

    /**
     * Create an instance of {@link Anschrift }
     * 
     */
    public Anschrift createAnschrift() {
        return new Anschrift();
    }

    /**
     * Create an instance of {@link Akteur }
     * 
     */
    public Akteur createAkteur() {
        return new Akteur();
    }

    /**
     * Create an instance of {@link Kommunikation }
     * 
     */
    public Kommunikation createKommunikation() {
        return new Kommunikation();
    }

    /**
     * Create an instance of {@link CodeBaumassnahmeArt }
     * 
     */
    public CodeBaumassnahmeArt createCodeBaumassnahmeArt() {
        return new CodeBaumassnahmeArt();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link CodeVorlagenBauantragBearbeitung }
     * 
     */
    public CodeVorlagenBauantragBearbeitung createCodeVorlagenBauantragBearbeitung() {
        return new CodeVorlagenBauantragBearbeitung();
    }

    /**
     * Create an instance of {@link Datenblatt }
     * 
     */
    public Datenblatt createDatenblatt() {
        return new Datenblatt();
    }

    /**
     * Create an instance of {@link CodeVorlagenBauantragBauvorhaben }
     * 
     */
    public CodeVorlagenBauantragBauvorhaben createCodeVorlagenBauantragBauvorhaben() {
        return new CodeVorlagenBauantragBauvorhaben();
    }

    /**
     * Create an instance of {@link CodeBaulicheAnlagenGebaeude }
     * 
     */
    public CodeBaulicheAnlagenGebaeude createCodeBaulicheAnlagenGebaeude() {
        return new CodeBaulicheAnlagenGebaeude();
    }

    /**
     * Create an instance of {@link CodeErleichterungGegenstand }
     * 
     */
    public CodeErleichterungGegenstand createCodeErleichterungGegenstand() {
        return new CodeErleichterungGegenstand();
    }

    /**
     * Create an instance of {@link CodeVorlagenBauzustand }
     * 
     */
    public CodeVorlagenBauzustand createCodeVorlagenBauzustand() {
        return new CodeVorlagenBauzustand();
    }

    /**
     * Create an instance of {@link NameNatuerlichePerson }
     * 
     */
    public NameNatuerlichePerson createNameNatuerlichePerson() {
        return new NameNatuerlichePerson();
    }

    /**
     * Create an instance of {@link CodeBenachrichtigungAnlass }
     * 
     */
    public CodeBenachrichtigungAnlass createCodeBenachrichtigungAnlass() {
        return new CodeBenachrichtigungAnlass();
    }

    /**
     * Create an instance of {@link FlurstueckKennzeichnung }
     * 
     */
    public FlurstueckKennzeichnung createFlurstueckKennzeichnung() {
        return new FlurstueckKennzeichnung();
    }

    /**
     * Create an instance of {@link CodeVorbescheidBetreff }
     * 
     */
    public CodeVorbescheidBetreff createCodeVorbescheidBetreff() {
        return new CodeVorbescheidBetreff();
    }

    /**
     * Create an instance of {@link BeteiligteBauprojektUmsetzung }
     * 
     */
    public BeteiligteBauprojektUmsetzung createBeteiligteBauprojektUmsetzung() {
        return new BeteiligteBauprojektUmsetzung();
    }

    /**
     * Create an instance of {@link VerwaltungspolitischeKodierung }
     * 
     */
    public VerwaltungspolitischeKodierung createVerwaltungspolitischeKodierung() {
        return new VerwaltungspolitischeKodierung();
    }

    /**
     * Create an instance of {@link Nebenbestimmung }
     * 
     */
    public Nebenbestimmung createNebenbestimmung() {
        return new Nebenbestimmung();
    }

    /**
     * Create an instance of {@link Nutzungseinheiten }
     * 
     */
    public Nutzungseinheiten createNutzungseinheiten() {
        return new Nutzungseinheiten();
    }

    /**
     * Create an instance of {@link VorbescheidBeantragt }
     * 
     */
    public VorbescheidBeantragt createVorbescheidBeantragt() {
        return new VorbescheidBeantragt();
    }

    /**
     * Create an instance of {@link CodeBauwerteGebaeudeartenPPVO }
     * 
     */
    public CodeBauwerteGebaeudeartenPPVO createCodeBauwerteGebaeudeartenPPVO() {
        return new CodeBauwerteGebaeudeartenPPVO();
    }

    /**
     * Create an instance of {@link IdentifikationNachricht }
     * 
     */
    public IdentifikationNachricht createIdentifikationNachricht() {
        return new IdentifikationNachricht();
    }

    /**
     * Create an instance of {@link CodeBundesland }
     * 
     */
    public CodeBundesland createCodeBundesland() {
        return new CodeBundesland();
    }

    /**
     * Create an instance of {@link CodeFormelleBefundeArt }
     * 
     */
    public CodeFormelleBefundeArt createCodeFormelleBefundeArt() {
        return new CodeFormelleBefundeArt();
    }

    /**
     * Create an instance of {@link AnliegenBeteiligung }
     * 
     */
    public AnliegenBeteiligung createAnliegenBeteiligung() {
        return new AnliegenBeteiligung();
    }

    /**
     * Create an instance of {@link CodeBautechnischerNachweisArt }
     * 
     */
    public CodeBautechnischerNachweisArt createCodeBautechnischerNachweisArt() {
        return new CodeBautechnischerNachweisArt();
    }

    /**
     * Create an instance of {@link BeteiligteBauprojektInPlanung }
     * 
     */
    public BeteiligteBauprojektInPlanung createBeteiligteBauprojektInPlanung() {
        return new BeteiligteBauprojektInPlanung();
    }

    /**
     * Create an instance of {@link CodeAnlassPruefungTechnischeAnlage }
     * 
     */
    public CodeAnlassPruefungTechnischeAnlage createCodeAnlassPruefungTechnischeAnlage() {
        return new CodeAnlassPruefungTechnischeAnlage();
    }

    /**
     * Create an instance of {@link CodeTechnischeAnlage }
     * 
     */
    public CodeTechnischeAnlage createCodeTechnischeAnlage() {
        return new CodeTechnischeAnlage();
    }

    /**
     * Create an instance of {@link CodeAmtlicherGemeindeschluessel }
     * 
     */
    public CodeAmtlicherGemeindeschluessel createCodeAmtlicherGemeindeschluessel() {
        return new CodeAmtlicherGemeindeschluessel();
    }

    /**
     * Create an instance of {@link CodeNebenbestimmungArt }
     * 
     */
    public CodeNebenbestimmungArt createCodeNebenbestimmungArt() {
        return new CodeNebenbestimmungArt();
    }

    /**
     * Create an instance of {@link Grundstuecksflaechen }
     * 
     */
    public Grundstuecksflaechen createGrundstuecksflaechen() {
        return new Grundstuecksflaechen();
    }

    /**
     * Create an instance of {@link Organisationseinheit }
     * 
     */
    public Organisationseinheit createOrganisationseinheit() {
        return new Organisationseinheit();
    }

    /**
     * Create an instance of {@link AllgemeinerName }
     * 
     */
    public AllgemeinerName createAllgemeinerName() {
        return new AllgemeinerName();
    }

    /**
     * Create an instance of {@link CodeXBauNachrichten }
     * 
     */
    public CodeXBauNachrichten createCodeXBauNachrichten() {
        return new CodeXBauNachrichten();
    }

    /**
     * Create an instance of {@link BauordnungsrechtlicheKlassifikation }
     * 
     */
    public BauordnungsrechtlicheKlassifikation createBauordnungsrechtlicheKlassifikation() {
        return new BauordnungsrechtlicheKlassifikation();
    }

    /**
     * Create an instance of {@link CodeBauvorlageberechtigungSachverhalt }
     * 
     */
    public CodeBauvorlageberechtigungSachverhalt createCodeBauvorlageberechtigungSachverhalt() {
        return new CodeBauvorlageberechtigungSachverhalt();
    }

    /**
     * Create an instance of {@link Geokodierung }
     * 
     */
    public Geokodierung createGeokodierung() {
        return new Geokodierung();
    }

    /**
     * Create an instance of {@link RefAnlage }
     * 
     */
    public RefAnlage createRefAnlage() {
        return new RefAnlage();
    }

    /**
     * Create an instance of {@link CodeBaulicheAnlagenSonstige }
     * 
     */
    public CodeBaulicheAnlagenSonstige createCodeBaulicheAnlagenSonstige() {
        return new CodeBaulicheAnlagenSonstige();
    }

    /**
     * Create an instance of {@link Baugrundstueck }
     * 
     */
    public Baugrundstueck createBaugrundstueck() {
        return new Baugrundstueck();
    }

    /**
     * Create an instance of {@link AbweichungBearbeitet }
     * 
     */
    public AbweichungBearbeitet createAbweichungBearbeitet() {
        return new AbweichungBearbeitet();
    }

    /**
     * Create an instance of {@link CodeGenehmigungsfreistellung }
     * 
     */
    public CodeGenehmigungsfreistellung createCodeGenehmigungsfreistellung() {
        return new CodeGenehmigungsfreistellung();
    }

    /**
     * Create an instance of {@link CodeAbweichungArt }
     * 
     */
    public CodeAbweichungArt createCodeAbweichungArt() {
        return new CodeAbweichungArt();
    }

    /**
     * Create an instance of {@link CodeBauwerksklasse }
     * 
     */
    public CodeBauwerksklasse createCodeBauwerksklasse() {
        return new CodeBauwerksklasse();
    }

    /**
     * Create an instance of {@link StaedtebaulicheKennzahlen }
     * 
     */
    public StaedtebaulicheKennzahlen createStaedtebaulicheKennzahlen() {
        return new StaedtebaulicheKennzahlen();
    }

    /**
     * Create an instance of {@link CodeErreichbarkeit }
     * 
     */
    public CodeErreichbarkeit createCodeErreichbarkeit() {
        return new CodeErreichbarkeit();
    }

    /**
     * Create an instance of {@link NachrichtG2G }
     * 
     */
    public NachrichtG2G createNachrichtG2G() {
        return new NachrichtG2G();
    }

    /**
     * Create an instance of {@link CodeBauweise }
     * 
     */
    public CodeBauweise createCodeBauweise() {
        return new CodeBauweise();
    }

    /**
     * Create an instance of {@link CodeStaat }
     * 
     */
    public CodeStaat createCodeStaat() {
        return new CodeStaat();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link Zahlungsdaten }
     * 
     */
    public Zahlungsdaten createZahlungsdaten() {
        return new Zahlungsdaten();
    }

    /**
     * Create an instance of {@link CodeGaragentyp }
     * 
     */
    public CodeGaragentyp createCodeGaragentyp() {
        return new CodeGaragentyp();
    }

    /**
     * Create an instance of {@link CodeXBauMimeType }
     * 
     */
    public CodeXBauMimeType createCodeXBauMimeType() {
        return new CodeXBauMimeType();
    }

    /**
     * Create an instance of {@link CodeBauwerteZuschlaegePPVO }
     * 
     */
    public CodeBauwerteZuschlaegePPVO createCodeBauwerteZuschlaegePPVO() {
        return new CodeBauwerteZuschlaegePPVO();
    }

    /**
     * Create an instance of {@link Staat }
     * 
     */
    public Staat createStaat() {
        return new Staat();
    }

    /**
     * Create an instance of {@link NameOrganisation }
     * 
     */
    public NameOrganisation createNameOrganisation() {
        return new NameOrganisation();
    }

    /**
     * Create an instance of {@link AnschriftBaugrundstueck }
     * 
     */
    public AnschriftBaugrundstueck createAnschriftBaugrundstueck() {
        return new AnschriftBaugrundstueck();
    }

    /**
     * Create an instance of {@link NachrichtenkopfG2G }
     * 
     */
    public NachrichtenkopfG2G createNachrichtenkopfG2G() {
        return new NachrichtenkopfG2G();
    }

    /**
     * Create an instance of {@link AmBauBeteiligtePerson }
     * 
     */
    public AmBauBeteiligtePerson createAmBauBeteiligtePerson() {
        return new AmBauBeteiligtePerson();
    }

    /**
     * Create an instance of {@link Kostenberechnung.Gebuehrenposition }
     * 
     */
    public Kostenberechnung.Gebuehrenposition createKostenberechnungGebuehrenposition() {
        return new Kostenberechnung.Gebuehrenposition();
    }

    /**
     * Create an instance of {@link Kostenberechnung.Auslagenposition }
     * 
     */
    public Kostenberechnung.Auslagenposition createKostenberechnungAuslagenposition() {
        return new Kostenberechnung.Auslagenposition();
    }

    /**
     * Create an instance of {@link Entwurfsverfasser.Bauvorlageberechtigung.Kammer }
     * 
     */
    public Entwurfsverfasser.Bauvorlageberechtigung.Kammer createEntwurfsverfasserBauvorlageberechtigungKammer() {
        return new Entwurfsverfasser.Bauvorlageberechtigung.Kammer();
    }

    /**
     * Create an instance of {@link AnlageBauvorlage.Bauvorlageart }
     * 
     */
    public AnlageBauvorlage.Bauvorlageart createAnlageBauvorlageBauvorlageart() {
        return new AnlageBauvorlage.Bauvorlageart();
    }

    /**
     * Create an instance of {@link BefundlistePruefungBauzustand.Befund }
     * 
     */
    public BefundlistePruefungBauzustand.Befund createBefundlistePruefungBauzustandBefund() {
        return new BefundlistePruefungBauzustand.Befund();
    }

    /**
     * Create an instance of {@link GeoreferenzierteLage.Flaeche }
     * 
     */
    public GeoreferenzierteLage.Flaeche createGeoreferenzierteLageFlaeche() {
        return new GeoreferenzierteLage.Flaeche();
    }

    /**
     * Create an instance of {@link BefundlisteFormell.Befund }
     * 
     */
    public BefundlisteFormell.Befund createBefundlisteFormellBefund() {
        return new BefundlisteFormell.Befund();
    }

    /**
     * Create an instance of {@link Bescheid.Tenor.KommentareFachrecht }
     * 
     */
    public Bescheid.Tenor.KommentareFachrecht createBescheidTenorKommentareFachrecht() {
        return new Bescheid.Tenor.KommentareFachrecht();
    }

    /**
     * Create an instance of {@link BefundlisteMateriell.Befund }
     * 
     */
    public BefundlisteMateriell.Befund createBefundlisteMateriellBefund() {
        return new BefundlisteMateriell.Befund();
    }

    /**
     * Create an instance of {@link BaulastErklaerung.Sachverhalt }
     * 
     */
    public BaulastErklaerung.Sachverhalt createBaulastErklaerungSachverhalt() {
        return new BaulastErklaerung.Sachverhalt();
    }

    /**
     * Create an instance of {@link Bauvorhaben.Verortung }
     * 
     */
    public Bauvorhaben.Verortung createBauvorhabenVerortung() {
        return new Bauvorhaben.Verortung();
    }

    /**
     * Create an instance of {@link Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage }
     * 
     */
    public Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage createBauvorhabenGegenstandArtDerBaulichenAnlage() {
        return new Bauvorhaben.Gegenstand.ArtDerBaulichenAnlage();
    }

}
