//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import de.xoev.schemata.code._1_0.Code;


/**
 * Eine Organisation ist eine  Vereinigung mehrerer natürlicher oder juristischer Personen bzw. eine rechtsfähige Personengesellschaft zu einem gemeinsamen Zweck, z.B.  im wirtschaftlichen, gemeinnützigen,  religiösen, öffentlichen oder politischen Bereich.
 * 
 * <p>Java class for Organisation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organisation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rechtsform" type="{http://xoev.de/schemata/code/1_0}Code" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.is-argebau.de/xbau/2}NameOrganisation"/>
 *         &lt;element name="anschrift" type="{http://www.is-argebau.de/xbau/2}Anschrift" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="kommunikation" type="{http://www.is-argebau.de/xbau/2}Kommunikation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="vertreter" type="{http://www.is-argebau.de/xbau/2}NameNatuerlichePerson" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organisation", propOrder = {
    "rechtsform",
    "name",
    "anschrift",
    "kommunikation",
    "vertreter"
})
public class Organisation {

    protected Code rechtsform;
    @XmlElement(required = true)
    protected NameOrganisation name;
    protected List<Anschrift> anschrift;
    protected List<Kommunikation> kommunikation;
    protected NameNatuerlichePerson vertreter;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the rechtsform property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getRechtsform() {
        return rechtsform;
    }

    /**
     * Sets the value of the rechtsform property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setRechtsform(Code value) {
        this.rechtsform = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameOrganisation }
     *     
     */
    public NameOrganisation getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameOrganisation }
     *     
     */
    public void setName(NameOrganisation value) {
        this.name = value;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anschrift property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnschrift().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Anschrift }
     * 
     * 
     */
    public List<Anschrift> getAnschrift() {
        if (anschrift == null) {
            anschrift = new ArrayList<Anschrift>();
        }
        return this.anschrift;
    }

    /**
     * Gets the value of the kommunikation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kommunikation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKommunikation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kommunikation }
     * 
     * 
     */
    public List<Kommunikation> getKommunikation() {
        if (kommunikation == null) {
            kommunikation = new ArrayList<Kommunikation>();
        }
        return this.kommunikation;
    }

    /**
     * Gets the value of the vertreter property.
     * 
     * @return
     *     possible object is
     *     {@link NameNatuerlichePerson }
     *     
     */
    public NameNatuerlichePerson getVertreter() {
        return vertreter;
    }

    /**
     * Sets the value of the vertreter property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameNatuerlichePerson }
     *     
     */
    public void setVertreter(NameNatuerlichePerson value) {
        this.vertreter = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
