//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.is-argebau.de/xbau/2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.is_argebau.xbau._2;
