//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ nimmt die Parameter einer Stellungnahme auf, mit der sich ein Antragsteller zu einem  belastenden Verwaltungsakt äußert.
 * 
 * <p>Java class for StellungnahmeBelastenderVerwaltungsakt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StellungnahmeBelastenderVerwaltungsakt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bezeichnungRegelverstoss" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/>
 *         &lt;element name="stellungnahme" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StellungnahmeBelastenderVerwaltungsakt", propOrder = {
    "bezeichnungRegelverstoss",
    "stellungnahme"
})
public class StellungnahmeBelastenderVerwaltungsakt {

    @XmlElement(required = true)
    protected String bezeichnungRegelverstoss;
    @XmlElement(required = true)
    protected Text stellungnahme;

    /**
     * Gets the value of the bezeichnungRegelverstoss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnungRegelverstoss() {
        return bezeichnungRegelverstoss;
    }

    /**
     * Sets the value of the bezeichnungRegelverstoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnungRegelverstoss(String value) {
        this.bezeichnungRegelverstoss = value;
    }

    /**
     * Gets the value of the stellungnahme property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getStellungnahme() {
        return stellungnahme;
    }

    /**
     * Sets the value of the stellungnahme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setStellungnahme(Text value) {
        this.stellungnahme = value;
    }

}
