//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import de.xoev.schemata.code._1_0.Code;


/**
 * Die Komponente "VerwaltungspolitischeKodierung" beinhaltet Information, die eine verwaltungspolitisch eindeutige Zuordnung ermöglichen.
 * 
 * <p>Java class for VerwaltungspolitischeKodierung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerwaltungspolitischeKodierung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kreis" type="{http://xoev.de/schemata/code/1_0}Code" minOccurs="0"/>
 *         &lt;element name="bezirk" type="{http://xoev.de/schemata/code/1_0}Code" minOccurs="0"/>
 *         &lt;element name="bundesland" type="{http://xoev.de/schemata/code/1_0}Code" minOccurs="0"/>
 *         &lt;element name="gemeindeschluessel" type="{http://xoev.de/schemata/code/1_0}Code" minOccurs="0"/>
 *         &lt;element name="regionalschluessel" type="{http://xoev.de/schemata/code/1_0}Code" minOccurs="0"/>
 *         &lt;element name="nation" type="{http://www.is-argebau.de/xbau/2}Staat" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerwaltungspolitischeKodierung", propOrder = {
    "kreis",
    "bezirk",
    "bundesland",
    "gemeindeschluessel",
    "regionalschluessel",
    "nation"
})
public class VerwaltungspolitischeKodierung {

    protected Code kreis;
    protected Code bezirk;
    protected Code bundesland;
    protected Code gemeindeschluessel;
    protected Code regionalschluessel;
    protected Staat nation;

    /**
     * Gets the value of the kreis property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getKreis() {
        return kreis;
    }

    /**
     * Sets the value of the kreis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setKreis(Code value) {
        this.kreis = value;
    }

    /**
     * Gets the value of the bezirk property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getBezirk() {
        return bezirk;
    }

    /**
     * Sets the value of the bezirk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setBezirk(Code value) {
        this.bezirk = value;
    }

    /**
     * Gets the value of the bundesland property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getBundesland() {
        return bundesland;
    }

    /**
     * Sets the value of the bundesland property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setBundesland(Code value) {
        this.bundesland = value;
    }

    /**
     * Gets the value of the gemeindeschluessel property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getGemeindeschluessel() {
        return gemeindeschluessel;
    }

    /**
     * Sets the value of the gemeindeschluessel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setGemeindeschluessel(Code value) {
        this.gemeindeschluessel = value;
    }

    /**
     * Gets the value of the regionalschluessel property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getRegionalschluessel() {
        return regionalschluessel;
    }

    /**
     * Sets the value of the regionalschluessel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setRegionalschluessel(Code value) {
        this.regionalschluessel = value;
    }

    /**
     * Gets the value of the nation property.
     * 
     * @return
     *     possible object is
     *     {@link Staat }
     *     
     */
    public Staat getNation() {
        return nation;
    }

    /**
     * Sets the value of the nation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Staat }
     *     
     */
    public void setNation(Staat value) {
        this.nation = value;
    }

}
