//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.is_argebau.xbau._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ beinhaltet die Parameter einer Frage, die im Rahmen eines Vorbescheidantrags thematisiert wird. Insoweit diese Frage einen Abweichungsantrag bzw. eine beantragte Erleichterung betrifft, sind in einer Instanz des Typs Daten enthalten, die den entsprechenden Kontext verdeutlichen.
 * 
 * <p>Java class for VorbescheidBeantragt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VorbescheidBeantragt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="artDerFrage" type="{http://www.is-argebau.de/xbau/2}Code.VorbescheidBetreff"/>
 *         &lt;element name="vorbescheidfrage" type="{http://www.is-argebau.de/xbau/2}Text"/>
 *         &lt;element name="beantragteAbweichung" type="{http://www.is-argebau.de/xbau/2}AbweichungBeantragt" minOccurs="0"/>
 *         &lt;element name="angefragteErleichterung" type="{http://www.is-argebau.de/xbau/2}ErleichterungAngefragt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VorbescheidBeantragt", propOrder = {
    "artDerFrage",
    "vorbescheidfrage",
    "beantragteAbweichung",
    "angefragteErleichterung"
})
public class VorbescheidBeantragt {

    @XmlElement(required = true)
    protected CodeVorbescheidBetreff artDerFrage;
    @XmlElement(required = true)
    protected Text vorbescheidfrage;
    protected AbweichungBeantragt beantragteAbweichung;
    protected ErleichterungAngefragt angefragteErleichterung;

    /**
     * Gets the value of the artDerFrage property.
     * 
     * @return
     *     possible object is
     *     {@link CodeVorbescheidBetreff }
     *     
     */
    public CodeVorbescheidBetreff getArtDerFrage() {
        return artDerFrage;
    }

    /**
     * Sets the value of the artDerFrage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeVorbescheidBetreff }
     *     
     */
    public void setArtDerFrage(CodeVorbescheidBetreff value) {
        this.artDerFrage = value;
    }

    /**
     * Gets the value of the vorbescheidfrage property.
     * 
     * @return
     *     possible object is
     *     {@link Text }
     *     
     */
    public Text getVorbescheidfrage() {
        return vorbescheidfrage;
    }

    /**
     * Sets the value of the vorbescheidfrage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Text }
     *     
     */
    public void setVorbescheidfrage(Text value) {
        this.vorbescheidfrage = value;
    }

    /**
     * Gets the value of the beantragteAbweichung property.
     * 
     * @return
     *     possible object is
     *     {@link AbweichungBeantragt }
     *     
     */
    public AbweichungBeantragt getBeantragteAbweichung() {
        return beantragteAbweichung;
    }

    /**
     * Sets the value of the beantragteAbweichung property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbweichungBeantragt }
     *     
     */
    public void setBeantragteAbweichung(AbweichungBeantragt value) {
        this.beantragteAbweichung = value;
    }

    /**
     * Gets the value of the angefragteErleichterung property.
     * 
     * @return
     *     possible object is
     *     {@link ErleichterungAngefragt }
     *     
     */
    public ErleichterungAngefragt getAngefragteErleichterung() {
        return angefragteErleichterung;
    }

    /**
     * Sets the value of the angefragteErleichterung property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErleichterungAngefragt }
     *     
     */
    public void setAngefragteErleichterung(ErleichterungAngefragt value) {
        this.angefragteErleichterung = value;
    }

}
