//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.meldeanschrift._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import de.osci.xinneres.codes.gemeindeverzeichnis._1.CodeGemeindeVZAmtlicherGemeindeschluessel;
import de.osci.xinneres.postanschrift._2.PostalischeInlandsanschriftBasis;


/**
 * Dieser Datentyp repräsentiert die gemeinsamen fachlichen Vorgaben der drei Standardisierungsbereiche Meldewesen, Ausländerwesen und Personenstandswesen für eine inländische Meldeanschrift auf der Grundlage des DSMeld.
 * Hinweis zu Hausnummernbereichen: Der DSMeld kennt keine Hausnummernbereiche. In diesen Fällen ist nur das erste Element des Hausnummernbereichs im Feld hausnummer einzutragen. Das zweite Element des Hausnummernbereichs kann in diesem Datentyp nicht übermittelt werden.
 * 
 * <p>Java class for Meldeanschrift complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Meldeanschrift">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gemeindeschluessel" type="{http://www.osci.de/xinneres/codes/gemeindeverzeichnis/1}Code.GemeindeVZ.AmtlicherGemeindeschluessel" minOccurs="0" form="unqualified"/>
 *         &lt;element name="hausnummer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Hausnummer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="hausnummerBuchstabeZusatzziffer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.HausnummerBuchstabeZusatzziffer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="postleitzahl" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Postleitzahl" minOccurs="0" form="unqualified"/>
 *         &lt;element name="stockwerkswohnungsnummer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Stockwerkswohnungsnummer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="strasse" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Strasse" minOccurs="0" form="unqualified"/>
 *         &lt;element name="teilnummerDerHausnummer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.TeilnummerDerHausnummer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="wohnort" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Wohnort" minOccurs="0" form="unqualified"/>
 *         &lt;element name="wohnortFruehererGemeindename" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.WohnortFruehererGemeindename" minOccurs="0" form="unqualified"/>
 *         &lt;element name="wohnungsinhaber" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Wohnungsinhaber" minOccurs="0" form="unqualified"/>
 *         &lt;element name="zusatzangaben" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Zusatzangaben" minOccurs="0" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Meldeanschrift", propOrder = {
    "gemeindeschluessel",
    "hausnummer",
    "hausnummerBuchstabeZusatzziffer",
    "postleitzahl",
    "stockwerkswohnungsnummer",
    "strasse",
    "teilnummerDerHausnummer",
    "wohnort",
    "wohnortFruehererGemeindename",
    "wohnungsinhaber",
    "zusatzangaben"
})
@XmlSeeAlso({
    PostalischeInlandsanschriftBasis.class
})
public class Meldeanschrift {

    protected CodeGemeindeVZAmtlicherGemeindeschluessel gemeindeschluessel;
    protected String hausnummer;
    protected String hausnummerBuchstabeZusatzziffer;
    protected String postleitzahl;
    protected String stockwerkswohnungsnummer;
    protected String strasse;
    protected String teilnummerDerHausnummer;
    protected String wohnort;
    protected String wohnortFruehererGemeindename;
    protected String wohnungsinhaber;
    protected String zusatzangaben;

    /**
     * Gets the value of the gemeindeschluessel property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGemeindeVZAmtlicherGemeindeschluessel }
     *     
     */
    public CodeGemeindeVZAmtlicherGemeindeschluessel getGemeindeschluessel() {
        return gemeindeschluessel;
    }

    /**
     * Sets the value of the gemeindeschluessel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGemeindeVZAmtlicherGemeindeschluessel }
     *     
     */
    public void setGemeindeschluessel(CodeGemeindeVZAmtlicherGemeindeschluessel value) {
        this.gemeindeschluessel = value;
    }

    /**
     * Gets the value of the hausnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHausnummer() {
        return hausnummer;
    }

    /**
     * Sets the value of the hausnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHausnummer(String value) {
        this.hausnummer = value;
    }

    /**
     * Gets the value of the hausnummerBuchstabeZusatzziffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHausnummerBuchstabeZusatzziffer() {
        return hausnummerBuchstabeZusatzziffer;
    }

    /**
     * Sets the value of the hausnummerBuchstabeZusatzziffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHausnummerBuchstabeZusatzziffer(String value) {
        this.hausnummerBuchstabeZusatzziffer = value;
    }

    /**
     * Gets the value of the postleitzahl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostleitzahl() {
        return postleitzahl;
    }

    /**
     * Sets the value of the postleitzahl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostleitzahl(String value) {
        this.postleitzahl = value;
    }

    /**
     * Gets the value of the stockwerkswohnungsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockwerkswohnungsnummer() {
        return stockwerkswohnungsnummer;
    }

    /**
     * Sets the value of the stockwerkswohnungsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockwerkswohnungsnummer(String value) {
        this.stockwerkswohnungsnummer = value;
    }

    /**
     * Gets the value of the strasse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrasse() {
        return strasse;
    }

    /**
     * Sets the value of the strasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrasse(String value) {
        this.strasse = value;
    }

    /**
     * Gets the value of the teilnummerDerHausnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeilnummerDerHausnummer() {
        return teilnummerDerHausnummer;
    }

    /**
     * Sets the value of the teilnummerDerHausnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeilnummerDerHausnummer(String value) {
        this.teilnummerDerHausnummer = value;
    }

    /**
     * Gets the value of the wohnort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWohnort() {
        return wohnort;
    }

    /**
     * Sets the value of the wohnort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWohnort(String value) {
        this.wohnort = value;
    }

    /**
     * Gets the value of the wohnortFruehererGemeindename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWohnortFruehererGemeindename() {
        return wohnortFruehererGemeindename;
    }

    /**
     * Sets the value of the wohnortFruehererGemeindename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWohnortFruehererGemeindename(String value) {
        this.wohnortFruehererGemeindename = value;
    }

    /**
     * Gets the value of the wohnungsinhaber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWohnungsinhaber() {
        return wohnungsinhaber;
    }

    /**
     * Sets the value of the wohnungsinhaber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWohnungsinhaber(String value) {
        this.wohnungsinhaber = value;
    }

    /**
     * Gets the value of the zusatzangaben property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZusatzangaben() {
        return zusatzangaben;
    }

    /**
     * Sets the value of the zusatzangaben property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZusatzangaben(String value) {
        this.zusatzangaben = value;
    }

}
