//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.basisnachricht._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import de.xoev.schemata.code._1_0.Code;


/**
 * Dieser Typ enthält die für die Identifikation einer Nachricht erforderlichen Informationen. Er kann verwendet werden, um
 * 
 *   Identifizierungsmerkmale zu setzen, auf die sich ein Nachrichtenempfänger beziehen kann (Verwendung im Nachrichtenkopf)   oder
 *   sich auf Identifizierungsmerkmale einer übermittelten Nachricht zu beziehen (Verwendung im Nachrichteninhalt von Reaktions- oder RtS-Nachrichten).
 * 
 * Darüber hinaus enthält der Typ den Erstellungszeitpunkt.
 * 
 * <p>Java class for Identifikation.Nachricht complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identifikation.Nachricht">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenUUID" type="{http://www.osci.de/xinneres/basisnachricht/3}UUID" form="unqualified"/>
 *         &lt;element name="nachrichtentyp" type="{http://xoev.de/schemata/code/1_0}Code" form="unqualified"/>
 *         &lt;element name="erstellungszeitpunkt" type="{http://www.w3.org/2001/XMLSchema}dateTime" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identifikation.Nachricht", propOrder = {
    "nachrichtenUUID",
    "nachrichtentyp",
    "erstellungszeitpunkt"
})
@XmlSeeAlso({
    de.is_argebau.xbau._2.IdentifikationNachricht.class,
    IdentifikationNachrichtTyp4 .class
})
public class IdentifikationNachricht {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String nachrichtenUUID;
    @XmlElement(required = true)
    protected Code nachrichtentyp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar erstellungszeitpunkt;

    /**
     * Gets the value of the nachrichtenUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNachrichtenUUID() {
        return nachrichtenUUID;
    }

    /**
     * Sets the value of the nachrichtenUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNachrichtenUUID(String value) {
        this.nachrichtenUUID = value;
    }

    /**
     * Gets the value of the nachrichtentyp property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getNachrichtentyp() {
        return nachrichtentyp;
    }

    /**
     * Sets the value of the nachrichtentyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setNachrichtentyp(Code value) {
        this.nachrichtentyp = value;
    }

    /**
     * Gets the value of the erstellungszeitpunkt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getErstellungszeitpunkt() {
        return erstellungszeitpunkt;
    }

    /**
     * Sets the value of the erstellungszeitpunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setErstellungszeitpunkt(XMLGregorianCalendar value) {
        this.erstellungszeitpunkt = value;
    }

}
