//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.basisnachricht._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Dieser Typ enthält Angaben, die ein Ereignis eindeutig identifizieren und es dem Leser einer Nachricht ermöglichen, die Reihenfolge von Ereignissen beim Autor nachzuvollziehen.
 * Sofern dieses Element in einer Nachricht mit mehreren Datensätzen verwendet wird (Sammelnachricht), dient es der Identifikation des Einzelfalls. Es  muss dann entsprechend für jeden Einzelfall in der Sammelnachricht übermittelt werden.
 * 
 * <p>Java class for Identifikation.Ereignis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Identifikation.Ereignis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ereignis.zeitpunkt" type="{http://www.w3.org/2001/XMLSchema}dateTime" form="unqualified"/>
 *         &lt;element name="ereignis.zeichen" type="{http://www.osci.de/xinneres/basisnachricht/3}Identifikation.Ereignis.Zeichen" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Identifikation.Ereignis", propOrder = {
    "ereignisZeitpunkt",
    "ereignisZeichen"
})
public class IdentifikationEreignis {

    @XmlElement(name = "ereignis.zeitpunkt", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ereignisZeitpunkt;
    @XmlElement(name = "ereignis.zeichen", required = true)
    protected String ereignisZeichen;

    /**
     * Gets the value of the ereignisZeitpunkt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEreignisZeitpunkt() {
        return ereignisZeitpunkt;
    }

    /**
     * Sets the value of the ereignisZeitpunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEreignisZeitpunkt(XMLGregorianCalendar value) {
        this.ereignisZeitpunkt = value;
    }

    /**
     * Gets the value of the ereignisZeichen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEreignisZeichen() {
        return ereignisZeichen;
    }

    /**
     * Sets the value of the ereignisZeichen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEreignisZeichen(String value) {
        this.ereignisZeichen = value;
    }

}
