//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.basisnachricht._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import de.osci.xinneres.behoerde._3.Behoerde;
import de.osci.xinneres.behoerde._3.BehoerdeErreichbar;


/**
 * Nachrichtenkopf für Nachrichten zwischen Behörden und anderen (öffentlichen) Stellen.
 * 
 * <p>Java class for Nachrichtenkopf.G2G complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Nachrichtenkopf.G2G">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifikation.nachricht" type="{http://www.osci.de/xinneres/basisnachricht/3}Identifikation.Nachricht" form="unqualified"/>
 *         &lt;element name="leser" type="{http://www.osci.de/xinneres/behoerde/3}Behoerde" form="unqualified"/>
 *         &lt;element name="autor" type="{http://www.osci.de/xinneres/behoerde/3}Behoerde.Erreichbar" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nachrichtenkopf.G2G", propOrder = {
    "identifikationNachricht",
    "leser",
    "autor"
})
@XmlSeeAlso({
    de.is_argebau.xbau._2.NachrichtenkopfG2G.class
})
public abstract class NachrichtenkopfG2G {

    @XmlElement(name = "identifikation.nachricht", required = true)
    protected IdentifikationNachricht identifikationNachricht;
    @XmlElement(required = true)
    protected Behoerde leser;
    @XmlElement(required = true)
    protected BehoerdeErreichbar autor;

    /**
     * Gets the value of the identifikationNachricht property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikationNachricht }
     *     
     */
    public IdentifikationNachricht getIdentifikationNachricht() {
        return identifikationNachricht;
    }

    /**
     * Sets the value of the identifikationNachricht property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikationNachricht }
     *     
     */
    public void setIdentifikationNachricht(IdentifikationNachricht value) {
        this.identifikationNachricht = value;
    }

    /**
     * Gets the value of the leser property.
     * 
     * @return
     *     possible object is
     *     {@link Behoerde }
     *     
     */
    public Behoerde getLeser() {
        return leser;
    }

    /**
     * Sets the value of the leser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Behoerde }
     *     
     */
    public void setLeser(Behoerde value) {
        this.leser = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link BehoerdeErreichbar }
     *     
     */
    public BehoerdeErreichbar getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehoerdeErreichbar }
     *     
     */
    public void setAutor(BehoerdeErreichbar value) {
        this.autor = value;
    }

}
