//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package net.opengis.gml._3;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class CartesianCSProperty
    extends JAXBElement<CartesianCSPropertyType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/gml/3.2", "cartesianCS");

    public CartesianCSProperty(CartesianCSPropertyType value) {
        super(NAME, ((Class) CartesianCSPropertyType.class), null, value);
    }

    public CartesianCSProperty() {
        super(NAME, ((Class) CartesianCSPropertyType.class), null, null);
    }

}
