//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package net.opengis.gml._3;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class PolarCSProperty
    extends JAXBElement<PolarCSPropertyType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/gml/3.2", "polarCS");

    public PolarCSProperty(PolarCSPropertyType value) {
        super(NAME, ((Class) PolarCSPropertyType.class), null, value);
    }

    public PolarCSProperty() {
        super(NAME, ((Class) PolarCSPropertyType.class), null, null);
    }

}
