//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.behoerde._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Die Behoerdenkennung fasst die Elemente zusammen, unter denen eine Behörde als Anbieter elektronischer Services im DVDV verzeichnet ist. Sie besteht aus einem Präfix und der eigentlichen Kennung. Grundsätzlich gibt es zu jedem Präfix eine entsprechende Schlüsseltabelle für die Kennung.
 * 
 * Zum Beispiel werden Standesämter über das Präfix psw und die Standesamtsnummer adressiert.
 * 
 * <p>Java class for Behoerdenkennung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Behoerdenkennung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="praefix" type="{http://www.osci.de/xinneres/behoerde/3}Code.Praefix" form="unqualified"/>
 *         &lt;element name="kennung" type="{http://www.osci.de/xinneres/behoerde/3}Code.Behoerdenkennung" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Behoerdenkennung", propOrder = {
    "praefix",
    "kennung"
})
public class Behoerdenkennung {

    @XmlElement(required = true)
    protected CodePraefix praefix;
    @XmlElement(required = true)
    protected CodeBehoerdenkennung kennung;

    /**
     * Gets the value of the praefix property.
     * 
     * @return
     *     possible object is
     *     {@link CodePraefix }
     *     
     */
    public CodePraefix getPraefix() {
        return praefix;
    }

    /**
     * Sets the value of the praefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodePraefix }
     *     
     */
    public void setPraefix(CodePraefix value) {
        this.praefix = value;
    }

    /**
     * Gets the value of the kennung property.
     * 
     * @return
     *     possible object is
     *     {@link CodeBehoerdenkennung }
     *     
     */
    public CodeBehoerdenkennung getKennung() {
        return kennung;
    }

    /**
     * Sets the value of the kennung property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeBehoerdenkennung }
     *     
     */
    public void setKennung(CodeBehoerdenkennung value) {
        this.kennung = value;
    }

}
