//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.behoerde._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Typ enthält Angaben über den Namen und die Erreichbarkeit einer Behörde. Eine Behörde  im Sinne des Verwaltungsverfahrensgesetzes ist jede Stelle, die Aufgaben der öffentlichen Verwaltung wahrnimmt.
 * Anders als in dem Typ Behoerde sind in diesem Typen alle Angaben zur Kontaktaufnahme mit der übermittelten Behörde Pflichtelemente.
 * 
 * <p>Java class for Behoerde.Erreichbar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Behoerde.Erreichbar">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.osci.de/xinneres/behoerde/3}Behoerde">
 *       &lt;sequence>
 *         &lt;element name="behoerdenkennung" type="{http://www.osci.de/xinneres/behoerde/3}Behoerdenkennung" form="unqualified"/>
 *         &lt;element name="erreichbarkeit" type="{http://www.osci.de/xinneres/kommunikation/2}Kommunikation" maxOccurs="unbounded" form="unqualified"/>
 *         &lt;element name="anschrift" type="{http://www.osci.de/xinneres/postanschrift/2}PostalischeInlandsanschrift" form="unqualified"/>
 *         &lt;element name="behoerdenname" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Behoerde.Erreichbar")
public class BehoerdeErreichbar
    extends Behoerde
{


}
