//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.behoerde._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import de.osci.xinneres.kommunikation._2.Kommunikation;
import de.osci.xinneres.postanschrift._2.PostalischeInlandsanschrift;


/**
 * Dieser Typ enthält Angaben über den Namen und die Erreichbarkeit einer Behörde. Eine Behörde  im Sinne des Verwaltungsverfahrensgesetzes ist jede Stelle, die Aufgaben der öffentlichen Verwaltung wahrnimmt.
 * 
 * <p>Java class for Behoerde complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Behoerde">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="behoerdenkennung" type="{http://www.osci.de/xinneres/behoerde/3}Behoerdenkennung" form="unqualified"/>
 *         &lt;element name="erreichbarkeit" type="{http://www.osci.de/xinneres/kommunikation/2}Kommunikation" maxOccurs="unbounded" minOccurs="0" form="unqualified"/>
 *         &lt;element name="anschrift" type="{http://www.osci.de/xinneres/postanschrift/2}PostalischeInlandsanschrift" minOccurs="0" form="unqualified"/>
 *         &lt;element name="behoerdenname" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Behoerde", propOrder = {
    "behoerdenkennung",
    "erreichbarkeit",
    "anschrift",
    "behoerdenname"
})
@XmlSeeAlso({
    BehoerdeErreichbar.class
})
public class Behoerde {

    @XmlElement(required = true)
    protected Behoerdenkennung behoerdenkennung;
    protected List<Kommunikation> erreichbarkeit;
    protected PostalischeInlandsanschrift anschrift;
    @XmlElement(required = true)
    protected String behoerdenname;

    /**
     * Gets the value of the behoerdenkennung property.
     * 
     * @return
     *     possible object is
     *     {@link Behoerdenkennung }
     *     
     */
    public Behoerdenkennung getBehoerdenkennung() {
        return behoerdenkennung;
    }

    /**
     * Sets the value of the behoerdenkennung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Behoerdenkennung }
     *     
     */
    public void setBehoerdenkennung(Behoerdenkennung value) {
        this.behoerdenkennung = value;
    }

    /**
     * Gets the value of the erreichbarkeit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the erreichbarkeit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErreichbarkeit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kommunikation }
     * 
     * 
     */
    public List<Kommunikation> getErreichbarkeit() {
        if (erreichbarkeit == null) {
            erreichbarkeit = new ArrayList<Kommunikation>();
        }
        return this.erreichbarkeit;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link PostalischeInlandsanschrift }
     *     
     */
    public PostalischeInlandsanschrift getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalischeInlandsanschrift }
     *     
     */
    public void setAnschrift(PostalischeInlandsanschrift value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the behoerdenname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehoerdenname() {
        return behoerdenname;
    }

    /**
     * Sets the value of the behoerdenname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehoerdenname(String value) {
        this.behoerdenname = value;
    }

}
