//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.postanschrift._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp beinhaltet die Angaben für die Adressierung im Inland, soweit es sich um eine Gebäudeanschrift (und nicht um eine Postfachanschrift) handelt.
 * 
 * <p>Java class for PostalischeInlandsanschrift.Gebaeudeanschrift complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostalischeInlandsanschrift.Gebaeudeanschrift">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.osci.de/xinneres/postanschrift/2}PostalischeInlandsanschrift.Basis">
 *       &lt;sequence>
 *         &lt;element name="hausnummern.bis" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hausnummer.bis" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Hausnummer" minOccurs="0"/>
 *                   &lt;element name="hausnummerbuchstabezusatzziffer.bis" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.HausnummerBuchstabeZusatzziffer" minOccurs="0"/>
 *                   &lt;element name="teilnummerderhausnummer.bis" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.TeilnummerDerHausnummer" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostalischeInlandsanschrift.Gebaeudeanschrift", propOrder = {
    "hausnummernBis"
})
public class PostalischeInlandsanschriftGebaeudeanschrift
    extends PostalischeInlandsanschriftBasis
{

    @XmlElement(name = "hausnummern.bis")
    protected PostalischeInlandsanschriftGebaeudeanschrift.HausnummernBis hausnummernBis;

    /**
     * Gets the value of the hausnummernBis property.
     * 
     * @return
     *     possible object is
     *     {@link PostalischeInlandsanschriftGebaeudeanschrift.HausnummernBis }
     *     
     */
    public PostalischeInlandsanschriftGebaeudeanschrift.HausnummernBis getHausnummernBis() {
        return hausnummernBis;
    }

    /**
     * Sets the value of the hausnummernBis property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalischeInlandsanschriftGebaeudeanschrift.HausnummernBis }
     *     
     */
    public void setHausnummernBis(PostalischeInlandsanschriftGebaeudeanschrift.HausnummernBis value) {
        this.hausnummernBis = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="hausnummer.bis" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Hausnummer" minOccurs="0"/>
     *         &lt;element name="hausnummerbuchstabezusatzziffer.bis" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.HausnummerBuchstabeZusatzziffer" minOccurs="0"/>
     *         &lt;element name="teilnummerderhausnummer.bis" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.TeilnummerDerHausnummer" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hausnummerBis",
        "hausnummerbuchstabezusatzzifferBis",
        "teilnummerderhausnummerBis"
    })
    public static class HausnummernBis {

        @XmlElement(name = "hausnummer.bis")
        protected String hausnummerBis;
        @XmlElement(name = "hausnummerbuchstabezusatzziffer.bis")
        protected String hausnummerbuchstabezusatzzifferBis;
        @XmlElement(name = "teilnummerderhausnummer.bis")
        protected String teilnummerderhausnummerBis;

        /**
         * Gets the value of the hausnummerBis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHausnummerBis() {
            return hausnummerBis;
        }

        /**
         * Sets the value of the hausnummerBis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHausnummerBis(String value) {
            this.hausnummerBis = value;
        }

        /**
         * Gets the value of the hausnummerbuchstabezusatzzifferBis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHausnummerbuchstabezusatzzifferBis() {
            return hausnummerbuchstabezusatzzifferBis;
        }

        /**
         * Sets the value of the hausnummerbuchstabezusatzzifferBis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHausnummerbuchstabezusatzzifferBis(String value) {
            this.hausnummerbuchstabezusatzzifferBis = value;
        }

        /**
         * Gets the value of the teilnummerderhausnummerBis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTeilnummerderhausnummerBis() {
            return teilnummerderhausnummerBis;
        }

        /**
         * Sets the value of the teilnummerderhausnummerBis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTeilnummerderhausnummerBis(String value) {
            this.teilnummerderhausnummerBis = value;
        }

    }

}
