//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.postanschrift._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import de.osci.xinneres.meldeanschrift._2.Meldeanschrift;


/**
 * Dieser Datentyp bildet die Basis einer postalischen Gebäudeanschrift. Er basiert auf der Meldeanschrift, enthält aber nur die für die Adressierung erforderlichen Angaben. Die Angabe des Wohnort, der Postleitzahl und der Straße sind in diesem Datentyp verpflichtend.
 * 
 * <p>Java class for PostalischeInlandsanschrift.Basis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostalischeInlandsanschrift.Basis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift">
 *       &lt;sequence>
 *         &lt;element name="hausnummer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Hausnummer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="hausnummerBuchstabeZusatzziffer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.HausnummerBuchstabeZusatzziffer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="postleitzahl" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Postleitzahl" form="unqualified"/>
 *         &lt;element name="stockwerkswohnungsnummer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Stockwerkswohnungsnummer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="strasse" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Strasse" form="unqualified"/>
 *         &lt;element name="teilnummerDerHausnummer" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.TeilnummerDerHausnummer" minOccurs="0" form="unqualified"/>
 *         &lt;element name="wohnort" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Wohnort" form="unqualified"/>
 *         &lt;element name="wohnortFruehererGemeindename" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.WohnortFruehererGemeindename" minOccurs="0" form="unqualified"/>
 *         &lt;element name="wohnungsinhaber" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Wohnungsinhaber" minOccurs="0" form="unqualified"/>
 *         &lt;element name="zusatzangaben" type="{http://www.osci.de/xinneres/meldeanschrift/2}Meldeanschrift.Zusatzangaben" minOccurs="0" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostalischeInlandsanschrift.Basis")
@XmlSeeAlso({
    PostalischeInlandsanschriftGebaeudeanschrift.class
})
public class PostalischeInlandsanschriftBasis
    extends Meldeanschrift
{


}
