//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 11:08:34 AM CEST 
//


package de.osci.xinneres.kommunikation._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Angaben zur Erreichbarkeit einer Behörde oder einer Person(Telefon, Fax, E-Mail, etc.).
 * 
 * <p>Java class for Kommunikation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Kommunikation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kanal" type="{http://www.osci.de/xinneres/kommunikation/2}Code.Erreichbarkeit" form="unqualified"/>
 *         &lt;element name="kennung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" form="unqualified"/>
 *         &lt;element name="zusatz" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kommunikation", propOrder = {
    "kanal",
    "kennung",
    "zusatz"
})
public class Kommunikation {

    @XmlElement(required = true)
    protected CodeErreichbarkeit kanal;
    @XmlElement(required = true)
    protected String kennung;
    protected String zusatz;

    /**
     * Gets the value of the kanal property.
     * 
     * @return
     *     possible object is
     *     {@link CodeErreichbarkeit }
     *     
     */
    public CodeErreichbarkeit getKanal() {
        return kanal;
    }

    /**
     * Sets the value of the kanal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeErreichbarkeit }
     *     
     */
    public void setKanal(CodeErreichbarkeit value) {
        this.kanal = value;
    }

    /**
     * Gets the value of the kennung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKennung() {
        return kennung;
    }

    /**
     * Sets the value of the kennung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKennung(String value) {
        this.kennung = value;
    }

    /**
     * Gets the value of the zusatz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZusatz() {
        return zusatz;
    }

    /**
     * Sets the value of the zusatz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZusatz(String value) {
        this.zusatz = value;
    }

}
